### ISSUE TITLE
Updated to latest 3.3 / 3.0, graphs not working and query log error, lists blank on web

### ISSUE THREAD

**Issue by Shadow00Caster** [pi-hole/pi-hole#1969]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
- 1

---
**Expected behaviour:**
- Normal operation

**Actual behaviour:**
- Dashboard shows no information
- Spinning refresh animation on graphs
- Whitelist and blacklist shows nothing
- Query log throws an error:
```
An unknown error occured while loading the data.
<br />
<b>Fatal error</b>:  Uncaught Error: Call to undefined function socket_create() in /var/www/html/admin/scripts/pi-hole/php/FTL.php:42
Stack trace:
#0 /var/www/html/admin/api_FTL.php(16): connectFTL('127.0.0.1')
#1 /var/www/html/admin/api.php(86): require('/var/www/html/a...')
#2 {main}
  thrown in <b>/var/www/html/admin/scripts/pi-hole/php/FTL.php</b> on line <b>42</b><br />
```
- Blocking appears to be working normally (dnsmasq), so this appears to just be a web issue

**Steps to reproduce:**
- Updated pihole through `pihole -up` on fully updated Debian 9 VM (running E1000 NIC due to VMXNET3 NIC issue)

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**
`a4s9g928nm`

**Troubleshooting undertaken, and/or other relevant information:**
- Flushed logs
- Restarted pihole systems and server

**Comment by maciboy** [comment]
I just experience something related:
On the web interface - after the update - it says:
Pi-hole Version v3.2.1 (Update available!) Web Interface Version v3.3 FTL Version v3.0

However, „pihole -up“ says all 3 components are up to date...

**Comment by Shadow00Caster** [comment]
@maciboy on my interface it shows correct version numbers:
![image](https://user-images.githubusercontent.com/13611109/36280585-98ca3422-124f-11e8-80e8-6703b86a14de.png)

**Comment by brotaxt** [comment]
Ive got exactly the same problems here on debian 8 :(

**Comment by C4Wiz** [comment]
i fixed the issue by running the following:

sudo rm /usr/bin/pihole-FTL
pihole -r

**Comment by Shadow00Caster** [comment]
@C4Wiz thanks for the suggestion, didn't work for me :(

**Comment by rafale77** [comment]
the pihole core fails to update to v3.3 with the `pihole -up` command

**Comment by dschaper** [comment]
`1e87850` is the 3.3 master release, see the tags fix on https://discourse.pi-hole.net/t/pi-hole-v3-3-released-its-extra-special/7159

**Comment by dschaper** [comment]
Debian 8 (Jessie) needs a rollback until we can fix the incompatible `dnsmasq` situation.

**Comment by Shadow00Caster** [comment]
@dschaper I'm on 9 latest fully updated.

**Comment by rafale77** [comment]
Hmm indeed the tag is the latest for 3.3 but why does it get reported as 3.2.1 then? Sorry I could not find a tag fix from the link to the blog.

**Comment by dschaper** [comment]
```
cd /etc/.pihole
sudo git fetch --tags
pihole -r
```

**Comment by maciboy** [comment]
My issue on 8/jessie is now resolved by fetching the tags 😄

**Comment by brotaxt** [comment]
After fetching the tags and removing the database-file under /etc/pihole (the webinteface still showed old entries) Its working on my debian 8 now :) although I still get an error when I start pihole-FTL:

`rm: cannot remove '/var/rum/pihole-FTL,sock': No such file or directory`

**Comment by Mcat12** [comment]
@brotaxt is that the exact output? The path is incorrect. (rum instead of run, comma instead of period).

**Comment by AlginMaduro** [comment]
for me clearing the browser cache helped.

**Comment by h2xtreme** [comment]
Having the same issue with debian 9.

dnsmasq seems to be working fine.

**Comment by SuNNjek** [comment]
I also have the problem on Raspbian but none of the solutions above helped. My debug token is ``6fzh285k3a``

**Comment by h2xtreme** [comment]
For me the solution was clean all the records in pihole-FTL.db

sqlite3 pihole-FTL.db

delete from queries;

systemctl restart pihole-FTL

But be advised that you will lose all your history.

**Comment by manikmagar** [comment]
I reverted back to previous version as suggested here - https://pi-hole.net/2018/02/14/pi-hole-v3-3-released-its-extra-special/.

Now, DNSMASQ as well as Dashboard works on raspberry os. Thanks.

**Comment by brotaxt** [comment]
@Mcat12 Sorry its a typo.

**Comment by Mcat12** [comment]
@Shadow00Caster your issue might have been overshadowed by the rest of the comments in this issue. It looks like your PHP doesn't support sockets? Try installing the `php-net-socket` package.

**Comment by Shadow00Caster** [comment]
@Mcat12 I installed `php-net-socket` as suggested and rebooted, still getting a PHP error:

```
An unknown error occured while loading the data.
<br />
<b>Fatal error</b>:  Uncaught Error: Call to undefined function socket_create() in /var/www/html/admin/scripts/pi-hole/php/FTL.php:42
Stack trace:
#0 /var/www/html/admin/api_FTL.php(16): connectFTL('127.0.0.1')
#1 /var/www/html/admin/api.php(86): require('/var/www/html/a...')
#2 {main}
  thrown in <b>/var/www/html/admin/scripts/pi-hole/php/FTL.php</b> on line <b>42</b><br />
```

**Comment by Shadow00Caster** [comment]
Also for info:
```
root@PH01:/etc/.pihole# php -v
PHP 7.0.27-0+deb9u1 (cli) (built: Jan  5 2018 13:51:52) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
```
```
root@PH01:/etc/.pihole# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.3 (stretch)
Release:        9.3
Codename:       stretch
```

**Comment by Mcat12** [comment]
Run `php --ini` and check the output to see if it includes a line like this (showing sockets are enabled):
```
/etc/php/7.0/cli/conf.d/20-sockets.ini
```

**Comment by Shadow00Caster** [comment]
@Mcat12  appears to be enabled.

```
root@PH01:~# php --ini
Configuration File (php.ini) Path: /etc/php/7.0/cli
Loaded Configuration File:         /etc/php/7.0/cli/php.ini
Scan for additional .ini files in: /etc/php/7.0/cli/conf.d
Additional .ini files parsed:      /etc/php/7.0/cli/conf.d/10-opcache.ini,
/etc/php/7.0/cli/conf.d/10-pdo.ini,
/etc/php/7.0/cli/conf.d/20-calendar.ini,
/etc/php/7.0/cli/conf.d/20-ctype.ini,
/etc/php/7.0/cli/conf.d/20-exif.ini,
/etc/php/7.0/cli/conf.d/20-fileinfo.ini,
/etc/php/7.0/cli/conf.d/20-ftp.ini,
/etc/php/7.0/cli/conf.d/20-gettext.ini,
/etc/php/7.0/cli/conf.d/20-iconv.ini,
/etc/php/7.0/cli/conf.d/20-json.ini,
/etc/php/7.0/cli/conf.d/20-pdo_sqlite.ini,
/etc/php/7.0/cli/conf.d/20-phar.ini,
/etc/php/7.0/cli/conf.d/20-posix.ini,
/etc/php/7.0/cli/conf.d/20-readline.ini,
/etc/php/7.0/cli/conf.d/20-shmop.ini,
/etc/php/7.0/cli/conf.d/20-sockets.ini,
/etc/php/7.0/cli/conf.d/20-sqlite3.ini,
/etc/php/7.0/cli/conf.d/20-sysvmsg.ini,
/etc/php/7.0/cli/conf.d/20-sysvsem.ini,
/etc/php/7.0/cli/conf.d/20-sysvshm.ini,
/etc/php/7.0/cli/conf.d/20-tokenizer.ini
```

**Comment by DL6ER** [comment]
What is the output of
```
php -i | grep "Sockets Support"
```
?

Sockets support is a compile time property of PHP and cannot be added by simply adding a module IIRC.

**Comment by framps** [comment]
Same to me. pihole ui worked fine for me until I upgraded to the latest version. I get a view of old data and that's it. Nothing serious because pihole filters all requests for my clients. But the UI is broken.

**Comment by xCozmox** [comment]
I have the same issue on my Raspberry pi 3 after running the command pihole -up.

But I have the impression that not everything is blocked anymore. At least I see some advertisement which I haven't seen before. Will further check. 

Definitely the Web-Interface is broken. Nothing is updated anymore. Graphs, logs, queries. 
Will try to rollback. 

Raspbian GNU/Linux 9 (stretch)
Pi-hole version is v3.2.1-73-g1e87850 (Latest: v3.3)
AdminLTE version is v3.3 (Latest: v3.3)
FTL version is v3.0 (Latest: v3.0)

**Comment by framps** [comment]
I just followed the [revert instructions](https://discourse.pi-hole.net/t/how-do-i-revert-to-a-previous-version-of-pi-hole/7168) and the UI works fine again :smile: Will monitor this issue now. 
If you want me to provide any debug info please let me know. I'll then install again the latest version again.

**Comment by xCozmox** [comment]
Ok. I got it working again by dschaper advice

> cd /etc/.pihole
> sudo git fetch --tags
> pihole -r

Than after pihole -v I have the following

 Pi-hole version is v3.3 (Latest: v3.3)
 AdminLTE version is v3.3 (Latest: v3.3)
 FTL version is v3.0 (Latest: v3.0)

But in my opinion there is somewhere a bug in the normal pihole -up

Seems that now everything works as expected. Will make some further checks.
