### ISSUE TITLE
Whitelisting domains does not work

### ISSUE THREAD

**Issue by NoobyNiceDev** [pi-hole/pi-hole#2041]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

Issue is duplicated e.g. 1657 or 571 but the Threads are closed and the solutions dont work for me.

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**
I expected, when I whitlist a domain in the pihole admin interface, I can open it.

**Actual behaviour:**

After Whitelisting a domain in the Admin-Interface, i still can't open/resolve it.

**Steps to reproduce:**

I can't open a web page.
Logged in into Admin interface -> Query-Log
Click Whitelist to specific domain (successfull)
flush DNS-cache and restart browser
still blocked
![blocked-pi-hole](https://user-images.githubusercontent.com/33202028/37564403-9ffe2e70-2a95-11e8-9b44-d084de81190b.PNG)

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

2mtq5zpxkw

**Troubleshooting undertaken, and/or other relevant information:**

My Ethernetconnection is just IPv4 ready and I just resolve IPv4 Adresses via slection of the upstream DNS Servers. I got the Error on various domains e.g. static.licdn.com

**Comment by PromoFaux** [comment]
Question, if the solutions in the other threads do not work, have you tried the` development` branch? 

`pihole checkout dev`, will get you onto it. (`pihole checkout master` if you want to revert to the released for any reason)

**Comment by NoobyNiceDev** [comment]
Sry, I wasn't specific enoughby explaining the duplicated Threads. The 1657 has exact the same discription, but the people asked him to read the cname entry (I would need to google what it is and how it works) and also to whitelist them. I think, that's not the way the whitelist shall work, not? And the solution for him was to use the original docker-container for his NAS. 
I'm using pi-hole on an Raspberry 3B, installed with the installation script.
The other issue was closed due to inactivity.

I don't want to checkout the "dev" branch. I'm just user, want to use "stable" (secure) software. In conclusion, there has been more than one report of that kind of bug but nobody tried to analyse it. I think, there is a bug. If you mention: If it don't run, reinstall it, then i could be a possible solution, but thats not the first step in my list :)

**Comment by PromoFaux** [comment]
>All blocklist hosted on s3.amazonaws.com couldn't be loaded...

Is `s3.amazonaws.com` on your blacklist? (`pihole -q s3.amazonaws.com`) 

The other ones downloaded OK though, right? the `development` branch as it stands is stable, it is the same as the `master` branch, but with some bug fixes for things that became apparent since we released 3.3. That's not to say it will always be stable, but it is currently stable enough to run as a daily driver. If it helps any, I'm always on `development` as my main pi-hole! But different strokes for different folks :)

**Comment by NoobyNiceDev** [comment]
No, s3.amazonaws.com ist just inside the downloaded blocklists, not explicit blacklisted.
It is just interesting, that the pihole itself couldn't download the blocklists, it has already worked in the past.
Now, I switched Back from Dev to Master branch and it works well again. During installation of the master branch he was able to download the blocklists again. 
In conclusion, the whitelisting struggled in a way, that a reboot of the pi didn't help. Only a reinstallation solved the problem.

**Comment by Gitulu** [comment]
Hello guys,

I have discovered an issue with the white listing function.
I use Pi Hole in the newest version 3.3 on an Debian VPS with a huge blocklist of "1,964,099" blocked domains.

Furthermore I have start to add the whitelist domains via SSH instead of the admin interface because of the bug I have read on your page. The whitelisting woks for a short time and not consequent.

For example I have whitelisted the domains "poloniex.com, bittrex.com".
But Pi Hole blocks it. 

![image](https://user-images.githubusercontent.com/35115314/37731231-dc37882e-2d41-11e8-84a6-d77128666841.png)

Furthermore I use a Coin block list: "https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/hosts" but normally the Whitelist should have prio before the blackist.

To help to find the bug I have generated a log, my token is: "bfql1kriyf".

If you need anything else please let me know.

Thank you

**Comment by Mcat12** [comment]
Have you made sure to flush your DNS cache before testing the domains? The change needs to propagate in the network before it stops getting blocked. The only error in your debug log that I saw was that you seem to have Apache listening on port 80 instead of lighttpd.

**Comment by NoobyNiceDev** [comment]
Ok, little additional info: issue #1965 deals the same issue, but no activity for one month.

**Comment by Gitulu** [comment]
Exactly this ticket #1965 looks like this.
Maybe I can figure out more and can provide you with a video.

**Comment by technicalpyro** [comment]
the issue is one with what locale the web interface uses and is fixed by #1996 that fix has been merged into the dev branch

**Comment by mustafasezgin** [comment]
Just an addition as Im experiencing this issue too. Im adding my whitelisted sites from the command line using pihole -w but I am still seeing pihole block my requests in the query log. 
The site is listed in the admin interface and trying to readd from the command line says it is whitelisted so nothing to do. Though the site is still being blocked.

**Comment by dstack4273** [comment]
@mustafasezgin - I had the same problem despite clearing caches and restarting services. I was able to get it working after removing the whitelisted domain from the gui, and then re-add it via command line.

**Comment by andrewtaehoon** [comment]
@mustafasezgin I used the command line to both remove and re-add the whitelisted domain. Restarted my local computer and that fixed the issue. It seems to be an issue with the web admin.
