### ISSUE TITLE
PiHole fails to install on Ubuntu Server

### ISSUE THREAD

**Issue by leonbrag** [pi-hole/pi-hole#2447]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [yes, on my machine it happens all the time] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

Expect to run "sudo curl -sSL https://install.pi-hole.net | sudo bash -x" to get PiHole isntalled

**Actual behaviour:**

Installation goes near instantly to 100% done without actually installing PiHole

1. install following version of Ubuntu"
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic

2. run "sudo curl -sSL https://install.pi-hole.net | sudo bash".

Here is output:

```
leonbrag@minlin:/etc$ sudo curl -sSL https://install.pi-hole.net | sudo bash -x
+ set -e
+ installLogLoc=/etc/pihole/install.log
+ setupVars=/etc/pihole/setupVars.conf
+ lighttpdConfig=/etc/lighttpd/lighttpd.conf
+ coltable=/opt/pihole/COL_TABLE
+ webInterfaceGitUrl=https://github.com/pi-hole/AdminLTE.git
+ webInterfaceDir=/var/www/html/admin
+ piholeGitUrl=https://github.com/pi-hole/pi-hole.git
+ PI_HOLE_LOCAL_REPO=/etc/.pihole
+ PI_HOLE_FILES=(chronometer list piholeDebug piholeLogFlush setupLCD update version gravity uninstall webpage)
+ PI_HOLE_INSTALL_DIR=/opt/pihole
+ PI_HOLE_CONFIG_DIR=/etc/pihole
+ useUpdateVars=false
+ adlistFile=/etc/pihole/adlists.list
+ regexFile=/etc/pihole/regex.list
+ IPV4_ADDRESS=
+ IPV6_ADDRESS=
+ QUERY_LOGGING=true
+ INSTALL_WEB_INTERFACE=true
+ '[' -z root ']'
++ stty size
++ echo 24 80
+ screen_size='24 80'
++ echo '24 80'
++ awk '{print $1}'
+ rows=24
++ awk '{print $2}'
++ echo '24 80'
+ columns=80
+ r=12
+ c=40
+ r=20
+ c=70
+ skipSpaceCheck=false
+ reconfigure=false
+ runUnattended=false
+ INSTALL_WEB_SERVER=true
+ [[ -f /opt/pihole/COL_TABLE ]]
+ COL_NC='\e[0m'
+ COL_LIGHT_GREEN='\e[1;32m'
+ COL_LIGHT_RED='\e[1;31m'
+ TICK='[\e[1;32m✓\e[0m]'
+ CROSS='[\e[1;31m✗\e[0m]'
+ INFO='[i]'
+ DONE='\e[1;32m done!\e[0m'
+ OVER='\r\033[K'
+ counter=0
+ [[ '' != true ]]
+ main
+ local 'str=Root user check'
+ echo ''

+ [[ 0 -eq 0 ]]
+ echo -e '  [\e[1;32m✓\e[0m] Root user check'
  [✓] Root user check
+ show_ascii_berry
+ echo -e '
        \e[1;32m.;;,.
        .ccccc:,.
         :cccclll:.      ..,,
          :ccccclll.   ;ooodc
           '\''ccll:;ll .oooodc
             .;cll.;;looo:.
                 \e[1;31m.. '\'','\''.
                .'\'',,,,,,'\''.
              .'\'',,,,,,,,,,.
            .'\'',,,,,,,,,,,,....
          ....'\'''\'''\'',,,,,,,'\''.......
        .........  ....  .........
        ..........      ..........
        ..........      ..........
        .........  ....  .........
          ........,,,,,,,'\''......
            ....'\'',,,,,,,,,,,,.
               .'\'',,,,,,,,,'\''.
                .'\'',,,,,,'\''.
                  ..'\'''\'''\''.\e[0m
'

        .;;,.
        .ccccc:,.
         :cccclll:.      ..,,
          :ccccclll.   ;ooodc
           'ccll:;ll .oooodc
             .;cll.;;looo:.
                 .. ','.
                .',,,,,,'.
              .',,,,,,,,,,.
            .',,,,,,,,,,,,....
          ....''',,,,,,,'.......
        .........  ....  .........
        ..........      ..........
        ..........      ..........
        .........  ....  .........
          ........,,,,,,,'......
            ....',,,,,,,,,,,,.
               .',,,,,,,,,'.
                .',,,,,,'.
                  ..'''.

+ make_temporary_log
++ mktemp /tmp/pihole_temp.XXXXXX
+ TEMPLOG=/tmp/pihole_temp.m7AJCJ
+ exec
+ rm /tmp/pihole_temp.m7AJCJ
+ distro_check
+ command -v apt-get
+ PKG_MANAGER=apt-get
+ UPDATE_PKG_CACHE='apt-get update'
+ PKG_INSTALL=(${PKG_MANAGER} --yes --no-install-recommends install)
+ PKG_COUNT='apt-get -s -o Debug::NoLocking=true upgrade | grep -c ^Inst || true'
+ apt-get install --dry-run iproute2
+ iproute_pkg=iproute2
+ command -v php
+ [[ '' != true ]]
+ apt-get install --dry-run php
+ phpVer=php
+ apt-get install --dry-run php-sqlite3
+ phpSqlite=sqlite3
+ INSTALLER_DEPS=(apt-utils dialog debconf dhcpcd5 git ${iproute_pkg} whiptail)
+ PIHOLE_DEPS=(bc cron curl dnsutils iputils-ping lsof netcat psmisc sudo unzip wget idn2 sqlite3 libcap2-bin dns-root-data resolvconf)
+ PIHOLE_WEB_DEPS=(lighttpd ${phpVer}-common ${phpVer}-cgi ${phpVer}-${phpSqlite})
+ LIGHTTPD_USER=www-data
+ LIGHTTPD_GROUP=www-data
+ LIGHTTPD_CFG=lighttpd.conf.debian
+ [[ -f /etc/pihole/setupVars.conf ]]
+ [[ false == true ]]
+ verifyFreeDiskSpace
+ local 'str=Disk space check'
+ local required_free_kilobytes=51200
+ local existing_free_kilobytes
++ df -Pk
++ grep -m1 '\/$'
++ awk '{print $4}'
+ existing_free_kilobytes=24173684
+ [[ 24173684 =~ ^([0-9])+$ ]]
+ [[ 24173684 -lt 51200 ]]
+ echo -e '  [\e[1;32m✓\e[0m] Disk space check'
  [✓] Disk space check
+ update_package_cache
+ local 'str=Update local cache of available packages'
+ echo ''

+ echo -ne '  [i] Update local cache of available packages...'
  [i] Update local cache of available packages...+ eval 'apt-get update'
+ echo -e '\r\033[K  [\e[1;32m✓\e[0m] Update local cache of available packages'
  [✓] Update local cache of available packages
+ notify_package_updates_available
+ local 'str=Checking apt-get for upgraded packages'
+ echo -ne '\n  [i] Checking apt-get for upgraded packages...'

  [i] Checking apt-get for upgraded packages...++ eval 'apt-get -s -o Debug::NoLocking=true upgrade | grep -c ^Inst || true'
+++ grep -c '^Inst'
+++ apt-get -s -o Debug::NoLocking=true upgrade
+++ true
+ updatesToInstall=0
++ uname -r
+ [[ -d /lib/modules/4.15.0-36-generic ]]
+ [[ 0 -eq 0 ]]
+ echo -e '\r\033[K  [\e[1;32m✓\e[0m] Checking apt-get for upgraded packages... up to date!'
  [✓] Checking apt-get for upgraded packages... up to date!
+ echo ''

+ install_dependent_packages 'INSTALLER_DEPS[@]'
+ counter=1
+ [[ 1 == 1 ]]
+ echo -e '  [i] Installer Dependency checks...'
  [i] Installer Dependency checks...
+ argArray1=("${!1}")
+ declare -a argArray1
+ declare -a installArray
+ command -v debconf-apt-progress
+ for i in "${argArray1[@]}"
+ echo -ne '  [i] Checking for apt-utils...'
  [i] Checking for apt-utils...+ grep 'ok installed'
+ dpkg-query -W '-f=${Status}' apt-utils
+ echo -e '\r\033[K  [\e[1;32m✓\e[0m] Checking for apt-utils'
  [✓] Checking for apt-utils
+ for i in "${argArray1[@]}"
+ echo -ne '  [i] Checking for dialog...'
  [i] Checking for dialog...+ dpkg-query -W '-f=${Status}' dialog
+ grep 'ok installed'
+ echo -e '\r\033[K  [i] Checking for dialog (will be installed)'
  [i] Checking for dialog (will be installed)
+ installArray+=("${i}")
+ for i in "${argArray1[@]}"
+ echo -ne '  [i] Checking for debconf...'
  [i] Checking for debconf...+ dpkg-query -W '-f=${Status}' debconf
+ grep 'ok installed'
+ echo -e '\r\033[K  [\e[1;32m✓\e[0m] Checking for debconf'
  [✓] Checking for debconf
+ for i in "${argArray1[@]}"
+ echo -ne '  [i] Checking for dhcpcd5...'
  [i] Checking for dhcpcd5...+ dpkg-query -W '-f=${Status}' dhcpcd5
+ grep 'ok installed'
+ echo -e '\r\033[K  [i] Checking for dhcpcd5 (will be installed)'
  [i] Checking for dhcpcd5 (will be installed)
+ installArray+=("${i}")
+ for i in "${argArray1[@]}"
+ echo -ne '  [i] Checking for git...'
  [i] Checking for git...+ dpkg-query -W '-f=${Status}' git
+ grep 'ok installed'
+ echo -e '\r\033[K  [\e[1;32m✓\e[0m] Checking for git'
  [✓] Checking for git
+ for i in "${argArray1[@]}"
+ echo -ne '  [i] Checking for iproute2...'
  [i] Checking for iproute2...+ dpkg-query -W '-f=${Status}' iproute2
+ grep 'ok installed'
+ echo -e '\r\033[K  [\e[1;32m✓\e[0m] Checking for iproute2'
  [✓] Checking for iproute2
+ for i in "${argArray1[@]}"
+ echo -ne '  [i] Checking for whiptail...'
  [i] Checking for whiptail...+ dpkg-query -W '-f=${Status}' whiptail
+ grep 'ok installed'
+ echo -e '\r\033[K  [\e[1;32m✓\e[0m] Checking for whiptail'
  [✓] Checking for whiptail
+ [[ 2 -gt 0 ]]
+ test_dpkg_lock
+ i=0
+ fuser /var/lib/dpkg/lock
+ return 0
+ debconf-apt-progress -- apt-get --yes --no-install-recommends install dialog dhcpcd5
```

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`{Alphanumeric token}`

**Troubleshooting undertaken, and/or other relevant information:**

Researched similar issues, retried install more then once.
Tried installing like this with the same results (near instant pink complete screen, without actual installation) 
wget -O basic-install.sh https://install.pi-hole.net
sudo bash basic-install.sh

**Comment by Mcat12** [comment]
Have you tried installing the packages marked for installation manually? You only got to the dependency checks, not 90% of the way through.

**Comment by leonbrag** [comment]
Not yet, it appears that there are instructions specific to 18.04. I will try following them.

What happens is there is web server already on the box (Ubiquiti UNMS In my case)?

Will PiHole co-exist with existing web server ?

Sent from my iPhone

On Oct 4, 2018, at 7:47 AM, Mark Drobnak <notifications@github.com<mailto:notifications@github.com>> wrote:


Have you tried installing the packages marked for installation manually? You only got to the dependency checks, not 90% of the way through.

**Comment by Mcat12** [comment]
Try installing the packages manually. If there's already a web server, that should not affect package installation (where you are at now). You will just need to change the port of the web server so they don't conflict.

**Comment by leonbrag** [comment]
I don’t think I understand which packages are missing. But will follow instructions from others who installed it on 18.04. 

Which web ports PiHole uses: 80 and 443 only for management ?

I will need to make sure UNMS does not conflict first.

**Comment by leonbrag** [comment]
Is there a UI during install to change PiHole ports? Alternatively is there a config file to change ports after install ?

Sent from my iPhone

On Oct 4, 2018, at 7:56 AM, Mark Drobnak <notifications@github.com<mailto:notifications@github.com>> wrote:


Try installing the packages manually. If there's already a web server, that should not affect package installation (where you are at now). You will just need to change the port of the web server so they don't conflict.

**Comment by Mcat12** [comment]
The packages marked something like the following are the ones that need to be installed:
> [i] Checking for dhcpcd5 (will be installed)

Pi-hole's web interface uses port 80, and has a config at `/etc/lighttpd/lighttpd.conf`. However it's recommended to change the other conflicting web server's port instead.

**Comment by leonbrag** [comment]
Solved by https://www.linuxincluded.com/install-pi-hole-on-ubuntu/

However it seems that install needs to be updated to work on 18.04 LTSB server

Hence leaving issue as open

**Comment by NatoBoram** [comment]
I just tried with a brand new installation of Ubuntu Server, and indeed, Pi-Hole doesn't install until the `sources.list` was modified to include more Ubuntu repositories. This issue is still valid.

**Comment by dschaper** [comment]
You should have been presented with a whiptail dialog asking if you would like to enable universe?

**Comment by effemmeffe** [comment]
Same issue here on ubuntu 18.04, even if I have universe in my sources.list.
I manually installed dhcpcd5.
I never got to the page where the admin password is displayed.
I also have apache installed, the files are in /var/wwww/html/admin, If I try to access to the web console I get an error:
Warning: parse_ini_file(/etc/pihole/setupVars.conf): failed to open stream: No such file or directory in /var/www/html/admin/scripts/pi-hole/php/password.php on line 15

**Comment by dschaper** [comment]
Did you disable the installation of the web interface and lighttpd?

**Comment by effemmeffe** [comment]
No. But after some digging it seems that I can't install lighttpd on my Ubuntu: https://askubuntu.com/questions/1112534/cant-install-lighttpd-on-ubuntu-18-04

**Comment by dschaper** [comment]
Fixed #2600
