### ISSUE TITLE
Pihole breaks lighttpd on Debian Buster

### ISSUE THREAD

**Issue by burnbabyburn** [pi-hole/pi-hole#2557]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1
---
**Expected behaviour:**

`Successful installation of pihole on a clean Debian 10 machine`

**Actual behaviour:**

`lighttpd isn't able to start WHILE and AFTER pihole installation => the lighttpd.conf file is broken. 
This results in the install script breaking without an error message.
Lighttpd is able to start before Pihole installation.`

**Install pihole:**

`Just install pihole with defaults AND webserver You still can install without lighttpd and use apache`

**Troubleshooting undertaken, and/or other relevant information:**
```
Dez 19 20:19:05 pihole lighttpd[17637]: /bin/sh: 1: /usr/share/lighttpd/create-mime.assign.pl: not found
Dez 19 20:19:05 pihole lighttpd[17637]: 2018-12-19 20:19:05: (configfile.c.1460) command "/usr/share/lighttpd/create-mime.assign.pl" exited non-zero: 127
Dez 19 20:19:05 pihole lighttpd[17637]: 2018-12-19 20:19:05: (configfile.c.1287) source: /etc/lighttpd/lighttpd.conf line: 53 pos: 14 parser failed somehow near here: (EOL)
```
The file was renamed to create-mime.conf.pl

```
root@pihole:/etc/lighttpd# ls -ahl /usr/share/lighttpd/
insgesamt 28K
drwxr-xr-x  2 root root 4,0K Dez 19 23:42 .
drwxr-xr-x 78 root root 4,0K Dez 19 23:42 ..
-rwxr-xr-x  1 root root 5,6K Nov 29 04:07 create-mime.conf.pl

```
After that lighttpd is able to start again. A lot of `Duplicate mimetype` messages appear but i think they also were in the default lighttpd install. 
```
Dez 19 23:46:34 pihole lighttpd[13199]: Duplicate mimetype: '.asn' => 'chemical/x-ncbi-asn1-spec' (already have 'chemical/x-ncbi-asn1'), merging to 'application/octet-stream'
Dez 19 23:46:34 pihole lighttpd[13199]: Duplicate mimetype: '.ent' => 'chemical/x-pdb' (already have 'chemical/x-ncbi-asn1-ascii'), merging to 'application/octet-stream'
Dez 19 23:46:34 pihole lighttpd[13199]: Duplicate mimetype: '.ttf' => 'font/otf' (already have 'application/font-sfnt'), merging to 'application/octet-stream'
Dez 19 23:46:34 pihole lighttpd[13199]: Duplicate mimetype: '.otf' => 'font/otf' (already have 'application/font-sfnt'), merging to 'application/octet-stream'
Dez 19 23:46:34 pihole lighttpd[13199]: Duplicate mimetype: '.woff' => 'font/woff' (already have 'application/font-woff'), merging to 'application/octet-stream'
```
A new version of lighttpd in debian was released yesterday https://tracker.debian.org/pkg/lighttpd thats propably the reason for this

**Comment by dschaper** [comment]
Debian Buster (10) or Debian Stretch (9.5)? If Buster (10) that's not a supported release and won't be until release freeze as we can't hit a moving target.

**Comment by neuffer** [comment]
Fix:
1. You probably lost the /etc/lighttpd/lighttpd.conf config and need to restore it.
Download it from https://raw.githubusercontent.com/pi-hole/pi-hole/master/advanced/lighttpd.conf.debian
Then fix up the include:
```
diff -uN lighttpd.conf.old lighttpd.conf
--- lighttpd.conf.old	2018-12-21 13:46:05.680535701 +0100
+++ lighttpd.conf	2018-12-21 13:43:40.736280842 +0100
@@ -46,7 +46,8 @@
 
 # default listening port for IPv6 falls back to the IPv4 port
 include_shell "/usr/share/lighttpd/use-ipv6.pl " + server.port
-include_shell "/usr/share/lighttpd/create-mime.assign.pl"
+#include_shell "/usr/share/lighttpd/create-mime.assign.pl"
+include_shell "/usr/share/lighttpd/create-mime.conf.pl"
 
 # Prevent Lighttpd from enabling Let's Encrypt SSL for every blocked domain
 #include_shell "/usr/share/lighttpd/include-conf-enabled.pl"

```

**Comment by LeonCB** [comment]
> 
> 
> Fix:
> 
>     1. You probably lost the /etc/lighttpd/lighttpd.conf config and need to restore it.
>        Download it from https://raw.githubusercontent.com/pi-hole/pi-hole/master/advanced/lighttpd.conf.debian
>        Then fix up the include:
> 
> 
> ```
> diff -uN lighttpd.conf.old lighttpd.conf
> --- lighttpd.conf.old	2018-12-21 13:46:05.680535701 +0100
> +++ lighttpd.conf	2018-12-21 13:43:40.736280842 +0100
> @@ -46,7 +46,8 @@
>  
>  # default listening port for IPv6 falls back to the IPv4 port
>  include_shell "/usr/share/lighttpd/use-ipv6.pl " + server.port
> -include_shell "/usr/share/lighttpd/create-mime.assign.pl"
> +#include_shell "/usr/share/lighttpd/create-mime.assign.pl"
> +include_shell "/usr/share/lighttpd/create-mime.conf.pl"
>  
>  # Prevent Lighttpd from enabling Let's Encrypt SSL for every blocked domain
>  #include_shell "/usr/share/lighttpd/include-conf-enabled.pl"
> ```

Thank you, this fix is working!

**Comment by victort** [comment]
a little bit more resistant to `pihole -up`, i did this alternative fix:

```
root@yellowlion:/usr/share/lighttpd# ln -s create-mime.assign.pl create-mime.conf.pl 
```

**Comment by billthefarmer** [comment]
Debian Buster is released, this still needed fixing.

**Comment by RamSet** [comment]
https://github.com/pi-hole/pi-hole/issues/2716#issuecomment-505104346

**Comment by dschaper** [comment]
It was released today, I actually just saw the image 2 hours ago, I'm sorry we haven't been able to release a new version in that time period.

**Comment by lafhq** [comment]
Installing on pi4 gives the same issue.
Used: /usr/share/lighttpd# ln -s create-mime.assign.pl create-mime.conf.pl

as a workarround

**Comment by ricktendo** [comment]
> 
> 
> Installing on pi4 gives the same issue.
> Used: /usr/share/lighttpd# ln -s create-mime.assign.pl create-mime.conf.pl
> 
> as a workarround

I tried this and received this error

`ln: failed to create symbolic link 'create-mime.conf.pl': File exists`

**Comment by billthefarmer** [comment]
I noticed it was the wrong way round but didn't say anything so as not to upset anyone else.
```shell
pi@jennifer:~ $ cd /usr/share/lighttpd/
pi@jennifer:/usr/share/lighttpd $ sudo ln -s create-mime.conf.pl create-mime.assign.pl
```

**Comment by dschaper** [comment]
See #2811

**Comment by Mcat12** [comment]
Fixed in v4.3.1

**Comment by procdaddy11** [comment]
Had issues after upgrading from 9 to 10. Decided to completely reinstall Debian and install pinhole from scratch. It’s still broken for me.

**Comment by dschaper** [comment]
Can you give us some details on what isn't working. Perhaps a debug token, or other log files and specifics so that we can try to fix it?

**Comment by procdaddy11** [comment]
Please disregard my last comment. http://pi.hole/admin/ works as expected.

**Comment by guidol70** [comment]
for the redirect-issue check the 404-error-handler change at
https://forum.armbian.com/topic/10398-info-pihole-lighttpd-issue-with-debian-buster/
