### ISSUE TITLE
Chrono on LCD Shows Error

### ISSUE THREAD

**Issue by gh0stshell** [pi-hole/pi-hole#299]
Been running fine for a while and the other night I went to check and got a runtime error, reset yesterday and today when I got home and checked it has the same error, not sure if this has to do with the other ticket. This only shows on the LCD as the script is always running on it verse the terminal.

Error on LCD Currently: Runtime Error (func=(main), adr=9): Divide by zero

**Comment by gh0stshell** [comment]
My setup has not changed and I only have added items to the whitelist

**Comment by jacobsalmela** [comment]
![2016-02-05 18 31 21](https://cloud.githubusercontent.com/assets/3843505/12937815/1a317f52-cf72-11e5-9a5f-99bbb3a67dd8.jpg)

**Comment by gh0stshell** [comment]
yup that would be it

**Comment by gh0stshell** [comment]
what screen size setting are you using? Mine still shows all the data on the LCD and is not cut off at the stop like your picture shows

**Comment by jacobsalmela** [comment]
the [2.8 TFT screen from Adafruit](http://amzn.to/1TdvMqi), but I adjusted the font size using `dpkg-reconfigure console-setup.`

**Comment by gh0stshell** [comment]
Sorry when I meant screen size I should have asked what setting do you use for the console-setup

**Comment by gh0stshell** [comment]
Did you always get the error? Mine just started happening.

**Comment by jacobsalmela** [comment]
Also, I'm almost done with a script that will auto-configure the LCD so you don't need to use Adfruits distro.

**Comment by gh0stshell** [comment]
cool...already have a bash script that does that, would like to see what you come up with

**Comment by PromoFaux** [comment]
Fixed here: af360a1

**Comment by gh0stshell** [comment]
Sorry guys, implemeted the fix and it went away for a while and now the error is back

**Comment by dschaper** [comment]
Do you want to reopen the issue and try some more? (I still don't have a screen, lol...)

**Comment by gh0stshell** [comment]
LOL, what was the fix so i can make sure i added the right one

**Comment by gh0stshell** [comment]
You want me to send you my extra? Still havent used it

**Comment by PromoFaux** [comment]
I know for sure that I squashed the divide by zero error [here](https://github.com/pi-hole/pi-hole/commit/4c24186911f01292932228c00b4f73bad4a94c0a)

But what I did notice [in this reddit thread](https://www.reddit.com/r/raspberry_pi/comments/45me85/pihole_help_chonometer_script_showing_errors/d00v3vw) about it, was the queries showing 0 even though there were 419 pi-holed queries...

**Comment by gh0stshell** [comment]
Was that after it hit midnight? I got that code submitted to dev a bit ago

**Comment by gh0stshell** [comment]
@PromoFaux , just emailed you

**Comment by gh0stshell** [comment]
Um...yeah.....I apparently looked at the wrong fix when the link was posted, I did not do that fix, give me a bit to add it to my pi-hole and I will give it a couple days to make sure

**Comment by gh0stshell** [comment]
My chrono section now looks like this:

function CalcPercentBlockedToday(){
        if [ "$queriesToday" != "Err." ] && [ "$blockedToday" != "Err." ]; then
        if [ "$queriesToday" != 0 ]; then #Fixes divide by zero error :)
                 #scale 2 rounds the number down, so we'll do scale 4 and then tr$
                        percentBlockedToday=$(echo "scale=4; $blockedToday/$queri$
                        percentBlockedToday=$(sed 's/.\{2\}$//' <<< "$percentBloc$
                else
                        percentBlockedToday=0
                fi
        fi
}

Did I miss anything?

**Comment by PromoFaux** [comment]
@gh0stshell Are you updated to 2.5.2? Because `chronometer.sh` in that has the fix for divide by zero.

Something looks off in your code block you just pasted in.. namely the ends of lines 4, 5, and 6...

**Comment by gh0stshell** [comment]
I am running the dev branch, would you like me to run the installer script again?

**Comment by gh0stshell** [comment]
error has not come up after adding the fix, the formatting and such may be off due to the way I pasted, what looks incorrect?

**Comment by gh0stshell** [comment]
keep closed, count still working correctly after time passes midnight, error no longer showing up, just need the right code fix, doh! my bad guys

**Comment by gh0stshell** [comment]
@PromoFaux could you explain to a coding newbie what that error meant?

**Comment by dschaper** [comment]
Do you mean, "What does a divide by zero error mean?"

**Comment by PromoFaux** [comment]
@gh0stshell 

To let [wikipedia explain the issue](https://en.wikipedia.org/wiki/Division_by_zero)

_**TL;DR;**_ it is impossible to divide by zero. Try it yourself on a calculator! `75 / 0 =`

Basically, when I re-wrote `chronometer.sh` I forgot to account for the fact that at the beginning of the day, there will be 0 queries. We use the number of queries to work out the percentage (`x/y*100` Where `x` is Pi-holed domains and `y` is total number of queries)

![image](https://cloud.githubusercontent.com/assets/1998970/13171698/1eda22e4-d6ec-11e5-92be-236f9dd999b3.png)

![image](https://cloud.githubusercontent.com/assets/1998970/13171770/77663b0a-d6ec-11e5-899a-f13c9dba88a0.png)

**Comment by gh0stshell** [comment]
Well that make complete sense, thanks! I was focused on the addr=9 error that I did not even try to look for the math errors. Highly appreciate the lesson!

**Comment by jacobsalmela** [comment]
@gh0stshell I made a PR for the [auto setup script for the LCD](https://github.com/pi-hole/pi-hole/blob/auto-chronometer-lcd-setup/advanced/Scripts/setupLCD.sh).

**Comment by gh0stshell** [comment]
nice! It will be way more elegant then mine, as a newbie coder I have been keeping it simple. I would like to wipe and reinstall and try everything once it ready, is it all in the dev branch? I have been using that for my installs so I get the latest updates.

**Comment by jacobsalmela** [comment]
@gh0stshell actually, it is [available now](https://github.com/pi-hole/pi-hole/blob/master/advanced/Scripts/setupLCD.sh).  I would love if you could try it out and give me any feedback.  It seems to work for me, but it would be nice to hear if it works for others or not.
