### ISSUE TITLE
Adding a static DHCP lease does not take effect until you restart the resolver

### ISSUE THREAD

**Issue by eglyn** [pi-hole/pi-hole#3063]
Hello all, 

I have an issue with static DHCP lease, it does not work...
When I add a MAC to an IP in the static lease section, pihole put another IP to this MAC...
I don't understand why...

[https://ibb.co/dD7jss6](url)

I tried to add same IP to the static lease, but when lease time expire, IP change :/

Any idea ?

Thx :)

**Comment by DL6ER** [comment]
Pi-hole's DHCP server tries to be deterministic, i.e., it always tries to assign the same IP to the same device (in contrast to enumerating them in the order of their appearance).

Try adding the lease, running `sudo service pihole-FTL restart` and then reconnect your device. Does Pi-hole honor the static assignment now?

**Comment by stephantual** [comment]
Came here to report this myself, can confirm that sudo service pihole-FTL restart is required before the changes are taken into account. It's quite confusing and probably could benefit from having an info message somewhere.

**Comment by gaevoc** [comment]
Can confirm this too, simply adding one row to the Static DHCP leases configuration is not enough, you need to restart pihole-FTL service

**Comment by relicash** [comment]
Whatever I do, restart router(dhcp disabled), clear leases on pihole, restart pihole-FTL.service, clear arp cache, some devices do not get the static ip. The device below is configured to use DHCP for network and doesn't have a static IP. I looked everywhere for a solution... 

Example:
more /etc/dnsmasq.d/04-pihole-static-dhcp.conf
dhcp-host=30:07:4D:EA:B1:B0,192.168.100.150,M-S7

more /etc/pihole/dhcp.leases
1585349820 30:07:4d:ea:b1:b0 192.168.100.137 Samsung-Galaxy-S7 01:30:07:4d:ea:b1:b0

more /var/log/pihole.log
Mar 26 19:05:45 dnsmasq-dhcp[14001]: DHCPDISCOVER(eth0) 30:07:4d:ea:b1:b0 
Mar 26 19:05:45 dnsmasq-dhcp[14001]: DHCPOFFER(eth0) 192.168.100.137 30:07:4d:ea:b1:b0 
Mar 26 19:05:45 dnsmasq-dhcp[14001]: DHCPREQUEST(eth0) 192.168.100.137 30:07:4d:ea:b1:b0 
Mar 26 19:05:45 dnsmasq-dhcp[14001]: DHCPACK(eth0) 192.168.100.137 30:07:4d:ea:b1:b0 Samsung-Galaxy-S7

Any ideas?

**Comment by pabclsn** [comment]
same here

**Comment by FaySmash** [comment]
+1, would be nice to receive a notification

**Comment by dschaper** [comment]
> +1, would be nice to receive a notification
Open a new issue and fill out the template in full.

Thanks

**Comment by DL6ER** [comment]
I forgot about looking at this as my to-do list was accidentally wiped earlier. Sorry.

**Comment by brockross** [comment]
Adding a +1 request for this feature--static DHCP additions via the UI appear not to work, which is a confusing experience. Same as others, running the ftl restart makes the new entries visible and functional in DHCP settings, query log, etc.

Thanks @DL6ER for all your hard work! Pihole is an excellent piece of software and it's clear you and the team have put a great deal of care and work into it.

**Comment by DL6ER** [comment]
Sorry for me forgetting about this (again) and thanks for the reminder. We added the ability to delete leases without a restart meanwhile. This turned out to be quite non-trivial (`dnsmasq` does not support it itself), however, I see we haven't implemented *adding* releases in the same manner. We *should* be able to implement adding similar to deleting, however, the API changes to expose this will be complicated. I'd prefer to implement this in the currently ongoing v6.0 development as this seems most effective.

**Comment by thebeanieman** [comment]
I wish I new this yesterday. If I had any hair left I would of pulled it all out.

I was adding a new device to the network, adding the MAC and IP. Disconnecting the device and reconnecting the device, it kept getting the original IP and not the new one. So for all 12 devices I added (1 by 1) I found myself adding the device, adding the mac and ip, restarting the pi and my cable model (prob did not need todo this).

Then I bumped into Apples Private Address "Feature" LOL!!!
https://support.apple.com/en-gb/HT211227
 
I did eventually get it all working how I wanted.

I am a web developer (17 years) and I really like what you lot are doing. Im considering offering some of my time to help you if I can. I have found a little UI glitch I would like to report, so thought I would check the issues before posting a new one, then found this which explains yesterdays "fun" ha.

Im interested in the v6.0 development, will look for more info.

**Comment by marcolvz** [comment]
> Pi-hole's DHCP server tries to be deterministic, i.e., it always tries to assign the same IP to the same device (in contrast to enumerating them in the order of their appearance).
> 
> Try adding the lease, running `sudo service pihole-FTL restart` and then reconnect your device. Does Pi-hole honor the static assignment now?

i'm having the same problem right now for only one of my leases (out of 2) and this method didn't work, any other solution?

**Comment by DL6ER** [comment]
@marcolvz If you have a `/etc/pihole/dhcp.leases` file, try editing this as well before restarting FTL. It may be that there still exists some older configuration that could take precedence.

**Comment by Spardz** [comment]
Disclaimer in the UI will be really helpful, I just spent a day before landing here.

**Comment by gavinsmith1971** [comment]
Is it really not possible to fix this after 3 years? It's clearly a bug - even a simple message that says you need to do something more than adding to the leases configuration list would be a start and avoid a lot of frustration for new users - like me!

**Comment by yubiuser** [comment]
I am sorry to hear it took so much time on your end and I also understand the frustration this is causing. Manually restarting the resolver will not be necessary in the next generation of Pi-hole (v6.0) which we expected to be released much earlier but - having only volunteers working on the project in their surplus time - this simply wasn't possible so far. Compared to other projects, it's much more important to us to deliver high-quality than fulfilling some artificial release milestones set to random dates.

As you may know, our team consists of a handful of dedicated developers who passionately contribute to our project alongside their "real life" responsibilities, including full-time jobs, family commitments, and other personal obligations. Their time is precious, and we are incredibly grateful for the effort they manage to invest.

At present, we are experiencing a significant backlog of updates and changes that are awaiting review further pushing the v6.0 release back. The volume of work is substantial, and given our limited resources, we are navigating through these as swiftly but also as thoroughly as possible. We are committed to maintaining the quality and integrity of our project, which means we cannot rush this process.

We understand that it may be frustrating to experience delays and slow turnaround times - even more when a bug report appears to have been forgotten for three years. Please know that we share in your eagerness to see progress and improvements but the v6.0 code is already around for several years and it is already fixed in there probably causing ourselves to not have a lot of attention here because we always expected things to get released much earlier. We ask for your patience and understanding as our team works diligently to address each change in the queue. It is unlikely that there will be another v5.x release.

___

See the small restart symbol, indication a automatic restart after changes to this setting have been changed.

![Screenshot at 2024-01-14 12-21-23](https://github.com/pi-hole/pi-hole/assets/26622301/c8c15620-92ba-4dc7-aeac-5226e7d3579d)

**Comment by gavinsmith1971** [comment]
> I am sorry to hear it took so much time on your end and I also understand the frustration this is causing. Manually restarting the resolver will not be necessary in the next generation of Pi-hole (v6.0) which we expected to be released much earlier but - having only volunteers working on the project in their surplus time - this simply wasn't possible so far. Compared to other projects, it's much more important to us to deliver high-quality than fulfilling some artificial release milestones set to random dates. 
 
> We understand that it may be frustrating to experience delays and slow turnaround times - even more when a bug report appears to have been forgotten for three years. Please know that we share in your eagerness to see progress and improvements but the v6.0 code is already around for several years and it is already fixed in there probably causing ourselves to not have a lot of attention here because we always expected things to get released much earlier. We ask for your patience and understanding as our team works diligently to address each change in the queue. It is unlikely that there will be another v5.x release.

I didn't want to sound ungrateful, I'm aware of how much time projects like this can take and I'm glad that it's fixed in the latest version.

I just wish that in an earlier update, there was something that had made it clear why it wasn't behaving as expected. Something as simple as changing the heading to "Static DHCP leases configuration (requires manual resolver restart to apply)" would have been enough.

Anyway, hopefully anyone else hitting the issue will find this page higher on Google than I did, and save themselves some time.

**Comment by freespiritstays** [comment]
Hi everyone, this seems to be an issue still, I am running two piholes one on the ubuntu  and another on Docker on the same machine, it took me almost a month to get Pihole to assign the first IP, and today I had spent all day trying to figure out why the IP reservation is being ignored.  Thanks for all your hard work and dedication

**Comment by yubiuser** [comment]
Pi-hole v6 has been released.
