### ISSUE TITLE
pihole -up cannot download the latest version of FTL which breaks it

### ISSUE THREAD

**Issue by llabas** [pi-hole/pi-hole#3710]
### Versions

- Pi-hole:  5.1.2
- AdminLTE:  5.1.1
- FTL:  5.0

### Platform

- OS and version:  Raspbian GNU/Linux 9 (stretch)

- Platform:   Raspberry Pi

### Expected behavior

pihole -up performs an upgrade

### Actual behavior / bug

  [i] FTL Checks...

  [‚úì] Detected ARM-hf architecture (armv7+)
  [i] Checking for existing FTL binary...
  [i] Downloading and Installing FTL...curl: (7) Failed to connect to github-production-release-asset-2e65be.s3.amazonaws.com port 443: Connection refused
  [‚úó] Downloading and Installing FTL
  Error: URL https://github.com/pi-hole/ftl/releases/latest/download/pihole-FTL-arm-linux-gnueabihf not found
  [‚úó] FTL Engine not installed

  Unable to complete update, please contact Pi-hole Support

### Steps to reproduce

Log into my PI
sudo -s
pihole -up

## Debug Token

- URL:  https://tricorder.pi-hole.net/0hv7koa0s3

### Screenshots

  [i] FTL Checks...

  [‚úì] Detected ARM-hf architecture (armv7+)
  [i] Checking for existing FTL binary...
  [i] Downloading and Installing FTL...curl: (7) Failed to connect to github-production-release-asset-2e65be.s3.amazonaws.com port 443: Connection refused
  [‚úó] Downloading and Installing FTL
  Error: URL https://github.com/pi-hole/ftl/releases/latest/download/pihole-FTL-arm-linux-gnueabihf not found
  [‚úó] FTL Engine not installed

  Unable to complete update, please contact Pi-hole Support

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by dschaper** [comment]
GitHub, are you awake yet?

**Comment by llabas** [comment]
Verified I still have the issue before running the curl again with the -iL.  No difference as @dschaper mentioned but wanted to be complete :)

root@cm0dns00:/home/pi# curl -IL https://github.com/pi-hole/pi-hole.git/
HTTP/1.1 301 Moved Permanently
date: Fri, 28 Aug 2020 00:45:38 GMT
content-type: text/html
content-length: 162
server: GitHub.com
location: https://github.com/pi-hole/pi-hole/
x-frame-options: DENY
vary: Accept-Encoding
Set-Cookie: _gh_sess=NvChVJNrsHhAd7Fe6IRcinyqSseKUKE9IY%2BeebdMy7mtmb4cv%2FDLrlQNrtU42Lq0P9wMZxMtUIkb467bjkAuf3T4ufAHqBtvwfATs6iH0HiEr5t4jlUj4jsnsf3dggV%2BnQj9iWuXa34Xom49yUDhdly8jzoIxBKB%2B2f6OsgycCXjSD%2BuFLLFsDg3bbqo54YrKcaw%2FNdv7SPDuQ68N0u6f%2FgSewRjZWodqbCj0PFhBf%2FwQ32FEUUugiPUwTxgs4ck80cRoew12LPJC97XyisqSg%3D%3D--5knRSyrtOQ6LC3ze--kvTnlBb8uf9z%2B05%2B%2BSjq2Q%3D%3D; Path=/; HttpOnly; Secure; SameSite=Lax
Set-Cookie: _octo=GH1.1.460832731.1598575538; Path=/; Domain=github.com; Expires=Sat, 28 Aug 2021 00:45:38 GMT; Secure; SameSite=Lax
Set-Cookie: logged_in=no; Path=/; Domain=github.com; Expires=Sat, 28 Aug 2021 00:45:38 GMT; HttpOnly; Secure; SameSite=Lax
X-GitHub-Request-Id: 3540:1979:A8252:ECDC6:5F4853B2

HTTP/1.1 200 OK
date: Fri, 28 Aug 2020 00:45:38 GMT
content-type: text/html; charset=utf-8
server: GitHub.com
status: 200 OK
vary: X-PJAX, Accept-Encoding, Accept, X-Requested-With, Accept-Encoding
etag: W/"745049d23ccdd3f3ce5156a28d3156d0"
cache-control: max-age=0, private, must-revalidate
strict-transport-security: max-age=31536000; includeSubdomains; preload
x-frame-options: deny
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
expect-ct: max-age=2592000, report-uri="https://api.github.com/_private/browser/errors"
content-security-policy: default-src 'none'; base-uri 'self'; block-all-mixed-content; connect-src 'self' uploads.github.com www.githubstatus.com collector.githubapp.com api.github.com www.google-analytics.com github-cloud.s3.amazonaws.com github-production-repository-file-5c1aeb.s3.amazonaws.com github-production-upload-manifest-file-7fdce7.s3.amazonaws.com github-production-user-asset-6210df.s3.amazonaws.com cdn.optimizely.com logx.optimizely.com/v1/events wss://alive.github.com; font-src github.githubassets.com; form-action 'self' github.com gist.github.com; frame-ancestors 'none'; frame-src render.githubusercontent.com; img-src 'self' data: github.githubassets.com identicons.github.com collector.githubapp.com github-cloud.s3.amazonaws.com *.githubusercontent.com; manifest-src 'self'; media-src 'none'; script-src github.githubassets.com; style-src 'unsafe-inline' github.githubassets.com; worker-src github.com/socket-worker.js gist.github.com/socket-worker.js
Set-Cookie: _gh_sess=ralTwXU7Fj90A0eEYLDKuZLTmJXSuYlyOMfu97%2FWofVpODu1dTZoYoMAyWqIQVNfybhOSZptd2dPDfougkq3bAFxs2k8gNo%2FXCqTng1RapxpvIiRux48Yknd0uFoS2X12NsY3s2bIsXrRPmwV5OJPeb2vvpeOVCFUA95WattjKfrU45IX5%2Bpka6MZbVKmopD4ba%2FstDpCi4pw7JGzfVmwvytNk0gbqveSW2BS2aJ4yGu8SVOzpRHkvWLByhephRiu6YkeOAVOX3VA9W16BfT0w%3D%3D--oDdmu0AxnE4fh7z1--IkRdwiUVawQmUM7tuQBn1g%3D%3D; Path=/; HttpOnly; Secure; SameSite=Lax
Set-Cookie: _octo=GH1.1.1827415954.1598575538; Path=/; Domain=github.com; Expires=Sat, 28 Aug 2021 00:45:38 GMT; Secure; SameSite=Lax
Set-Cookie: logged_in=no; Path=/; Domain=github.com; Expires=Sat, 28 Aug 2021 00:45:38 GMT; HttpOnly; Secure; SameSite=Lax
Accept-Ranges: bytes
X-GitHub-Request-Id: 3540:1979:A8254:ECDCA:5F4853B2

**Comment by yubiuser** [comment]
Maybe this is the curl IPv6 glitch?
https://discourse.pi-hole.net/t/cant-update-from-5-0-claims-cant-get-update-file-but-i-can-get-it-via-wget/33842/2?u=yubiuser
https://unix.stackexchange.com/questions/90742/curl-with-ipv6-not-working-by-default/90745#90745

**Comment by llabas** [comment]
My ISP does not support IPV6 yet, nor do I have it configured.

As of this morning, it's now working.

  [i] FTL Checks...

  [‚úì] Detected ARM-hf architecture (armv7+)
  [i] Checking for existing FTL binary...
  [‚úì] Downloading and Installing FTL
  [‚úì] Installing scripts from /etc/.pihole

  [i] Installing configs from /etc/.pihole...
  [i] Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!
  [‚úì] Copying 01-pihole.conf to /etc/dnsmasq.d/01-pihole.conf

  [i] Installing blocking page...
  [‚úì] Creating directory for blocking page, and copying files
  [i] Backing up index.lighttpd.html
      No default index.lighttpd.html file found... not backing up

  [‚úì] Installing sudoer file

  [‚úì] Installing latest Cron script

  [‚úì] Installing latest logrotate script
  [i] Backing up /etc/dnsmasq.conf to /etc/dnsmasq.conf.old
  [‚úì] man pages installed and database updated
  [i] Testing if systemd-resolved is enabled
  [i] Systemd-resolved is not enabled
  [‚úì] Restarting lighttpd service...
  [‚úì] Enabling lighttpd service to start on reboot...
  [i] Restarting services...
  [‚úì] Enabling pihole-FTL service to start on reboot...
  [‚úì] Restarting pihole-FTL service...
  [‚úì] Deleting existing list cache
  [i] Neutrino emissions detected...
  [‚úì] Pulling blocklist source list into range

  [‚úì] Preparing new gravity database
  [i] Target: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  [‚úì] Status: Retrieval successful
  [i] Received 55654 domains

  [i] Target: https://mirror1.malwaredomains.com/files/justdomains
  [‚úì] Status: Retrieval successful
  [i] Received 26854 domains

  [i] Target: http://sysctl.org/cameleon/hosts
  [‚úì] Status: Retrieval successful
  [i] Received 20567 domains

  [i] Target: https://zeustracker.abuse.ch/blocklist.php?download=domainblocklist
  [‚úì] Status: Retrieval successful
  [i] Received 0 domains

  [i] Target: https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
  [‚úì] Status: Retrieval successful
  [i] Received 34 domains

  [i] Target: https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
  [‚úì] Status: Retrieval successful
  [i] Received 2701 domains

  [i] Target: https://hosts-file.net/ad_servers.txt
  [‚úó] Status: Not found
  [‚úó] List download failed: no cached list available

  [‚úì] Storing downloaded domains in new gravity database
  [‚úì] Building tree
  [‚úì] Swapping databases
  [i] Number of gravity domains: 105810 (93492 unique domains)
  [i] Number of exact blacklisted domains: 0
  [i] Number of regex blacklist filters: 0
  [i] Number of exact whitelisted domains: 30
  [i] Number of regex whitelist filters: 1
  [‚úì] Flushing DNS cache
  [‚úì] Cleaning up stray matter

  [‚úì] DNS service is running
  [‚úì] Pi-hole blocking is Enabled

  [i] The install log is located at: /etc/pihole/install.log
Update Complete! 

  Current Pi-hole version is v5.1.2.
  Current AdminLTE version is v5.1.1.
  Current FTL version is v5.2.

**Comment by yubiuser** [comment]
Prefect. So this is solved then?

**Comment by llabas** [comment]
I made no changes so the question is what changed to fix it?

From google it seems this has happened before so perhaps finding the problem can lead to a prevention?

**Comment by elhennig** [comment]
For me the update still fails with
curl: (7) Failed to connect to github-production-release-asset-2e65be.s3.amazonaws.com port 443: Die Wartezeit für die Verbindung ist abgelaufen
So the connection times out...

**Comment by dschaper** [comment]
Does clicking on that link open the file in your browser?

**Comment by elhennig** [comment]
I guess it opened a xml file, but the problem seems to be solved, the update routine is working again

**Comment by elhennig** [comment]
The problem is back, again. Very strange, the timeout for the update check on FTL is again happening.
The xml file has the following content:
`<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>E951E02B8F8643C5</RequestId>
<HostId>
G32WQTrJo10Il0n7bw6a1c9gkQbYbjN1+ZWAlWvqV4AtdoSdNn2+snUNAwVdXoor+eaRvpRjFRs=
</HostId>
</Error>`

**Comment by yubiuser** [comment]
The original problem for the OP was solved.

If @elhennig still experience issues, please open a new ticket
