### ISSUE TITLE
5.2 disables DNS service

### ISSUE THREAD

**Issue by jasonbayton** [pi-hole/pi-hole#3871]
### Versions

- Pi-hole:  5.2
- AdminLTE:  5.2
- FTL:  5.1.2

### Platform

- OS and version:  Ubuntu 20.10

- Platform:  VM

### Expected behavior

When installing 5.2, both as an upgrade from 5.1.2 (vm1) and new install (vm2), DNS service should work by default

### Actual behavior / bug

Following the upgrade to 5.1.2 the DNS service didn't re-enable. The new install on 5.2 didn't enable the DNS service to begin with.

### Steps to reproduce

Upgrade from 5.1.2 (pinhole -up)
Or new install

## Debug Token

- URL:  https://tricorder.pi-hole.net/svvso3mdm1

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

I've checked to ensure dnsmasq is not present. 
Pinhole-ftl tells me the address is already in use in both VMs
53 is listed in netstat with no process assigned to it

**Comment by FilipFrancis** [comment]
Same issue here running pi-hole on centos 7
did upgrade pi-hole seems to be running but its not adding the resolvers that i put in place
even clean install same thing no dns resolvers added
i saw this by running pihole-FTL -f i see the following
[2020-11-29 10:07:00.375 72712M] Using log file /var/log/pihole-FTL.log
[2020-11-29 10:07:00.375 72712M] ########## FTL started! ##########
[2020-11-29 10:07:00.376 72712M] FTL branch: master
[2020-11-29 10:07:00.376 72712M] FTL version: v5.3.1
[2020-11-29 10:07:00.376 72712M] FTL commit: e1db31d
[2020-11-29 10:07:00.376 72712M] FTL date: 2020-11-28 21:59:12 +0100
[2020-11-29 10:07:00.376 72712M] FTL user: root
[2020-11-29 10:07:00.376 72712M] Compiled for x86_64 (compiled on CI) using gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
[2020-11-29 10:07:00.376 72712M] Starting config file parsing (/etc/pihole/pihole-FTL.conf)
[2020-11-29 10:07:00.376 72712M]    SOCKET_LISTENING: only local
[2020-11-29 10:07:00.376 72712M]    AAAA_QUERY_ANALYSIS: Show AAAA queries
[2020-11-29 10:07:00.376 72712M]    MAXDBDAYS: max age for stored queries is 365 days
[2020-11-29 10:07:00.376 72712M]    RESOLVE_IPV6: Resolve IPv6 addresses
[2020-11-29 10:07:00.376 72712M]    RESOLVE_IPV4: Resolve IPv4 addresses
[2020-11-29 10:07:00.376 72712M]    DBINTERVAL: saving to DB file every minute
[2020-11-29 10:07:00.377 72712M]    DBFILE: Using /etc/pihole/pihole-FTL.db
[2020-11-29 10:07:00.377 72712M]    MAXLOGAGE: Importing up to 24.0 hours of log data
[2020-11-29 10:07:00.377 72712M]    PRIVACYLEVEL: Set to 0
[2020-11-29 10:07:00.377 72712M]    IGNORE_LOCALHOST: Show queries from localhost
[2020-11-29 10:07:00.377 72712M]    BLOCKINGMODE: Null IPs for blocked domains
[2020-11-29 10:07:00.377 72712M]    ANALYZE_ONLY_A_AND_AAAA: Disabled. Analyzing all queries
[2020-11-29 10:07:00.377 72712M]    DBIMPORT: Importing history from database
[2020-11-29 10:07:00.377 72712M]    PIDFILE: Using /run/pihole-FTL.pid
[2020-11-29 10:07:00.377 72712M]    PORTFILE: Using /run/pihole-FTL.port
[2020-11-29 10:07:00.377 72712M]    SOCKETFILE: Using /run/pihole/FTL.sock
[2020-11-29 10:07:00.377 72712M]    SETUPVARSFILE: Using /etc/pihole/setupVars.conf
[2020-11-29 10:07:00.378 72712M]    MACVENDORDB: Using /etc/pihole/macvendor.db
[2020-11-29 10:07:00.378 72712M]    GRAVITYDB: Using /etc/pihole/gravity.db
[2020-11-29 10:07:00.378 72712M]    PARSE_ARP_CACHE: Active
[2020-11-29 10:07:00.378 72712M]    CNAME_DEEP_INSPECT: Active
[2020-11-29 10:07:00.378 72712M]    DELAY_STARTUP: No delay requested.
[2020-11-29 10:07:00.378 72712M]    BLOCK_ESNI: Enabled, blocking _esni.{blocked domain}
[2020-11-29 10:07:00.378 72712M]    NICE: Set process niceness to -10 (default)
[2020-11-29 10:07:00.378 72712M]    MAXNETAGE: Removing IP addresses and host names from network table after 365 days
[2020-11-29 10:07:00.378 72712M]    NAMES_FROM_NETDB: Enabled, trying to get names from network database
[2020-11-29 10:07:00.378 72712M]    EDNS0_ECS: Overwrite client from ECS information
[2020-11-29 10:07:00.378 72712M] Finished config file parsing
[2020-11-29 10:07:00.379 72712M] Creating mutex
[2020-11-29 10:07:00.381 72712M] WARNING: Starting pihole-FTL as user root is not recommended
[2020-11-29 10:07:00.382 72712M] Database version is 9
[2020-11-29 10:07:00.382 72712M] Imported 0 alias-clients
[2020-11-29 10:07:00.383 72712M] Database successfully initialized
[2020-11-29 10:07:00.383 72712M] Imported 0 queries from the long-term database
[2020-11-29 10:07:00.383 72712M]  -> Total DNS queries: 0
[2020-11-29 10:07:00.383 72712M]  -> Cached DNS queries: 0
[2020-11-29 10:07:00.383 72712M]  -> Forwarded DNS queries: 0
[2020-11-29 10:07:00.383 72712M]  -> Blocked DNS queries: 0
[2020-11-29 10:07:00.383 72712M]  -> Unknown DNS queries: 0
[2020-11-29 10:07:00.383 72712M]  -> Unique domains: 0
[2020-11-29 10:07:00.383 72712M]  -> Unique clients: 0
[2020-11-29 10:07:00.384 72712M]  -> Known forward destinations: 0
[2020-11-29 10:07:00.384 72712M] Successfully accessed setupVars.conf
[2020-11-29 10:07:00.387 72712M] PID of FTL process: 72712
[2020-11-29 10:07:00.388 72712/T72714] Listening on port 4711 for incoming IPv4 telnet connections
[2020-11-29 10:07:00.389 72712/T72716] Listening on Unix socket
[2020-11-29 10:07:00.389 72712/T72715] Listening on port 4711 for incoming IPv6 telnet connections
[2020-11-29 10:07:00.389 72712M] INFO: FTL is going to drop from root to user root (UID 0)
[2020-11-29 10:07:00.390 72712M] Changing FTL-lock (15) to 0:0
[2020-11-29 10:07:00.390 72712M] Changing FTL-strings (15) to 0:0
[2020-11-29 10:07:00.390 72712M] Changing FTL-counters (15) to 0:0
[2020-11-29 10:07:00.390 72712M] Changing FTL-domains (15) to 0:0
[2020-11-29 10:07:00.390 72712M] Changing FTL-clients (15) to 0:0
[2020-11-29 10:07:00.390 72712M] Changing FTL-queries (15) to 0:0
[2020-11-29 10:07:00.390 72712M] Changing FTL-upstreams (15) to 0:0
[2020-11-29 10:07:00.390 72712M] Changing FTL-overTime (15) to 0:0
[2020-11-29 10:07:00.390 72712M] Changing FTL-settings (15) to 0:0
[2020-11-29 10:07:00.390 72712M] Changing FTL-dns-cache (15) to 0:0
[2020-11-29 10:07:00.390 72712M] Changing FTL-per-client-regex (15) to 0:0
But whn i use my other pihole system and run the sam command i see this
[2020-11-29 10:14:14.977 966940M] Using log file /var/log/pihole-FTL.log
[2020-11-29 10:14:14.977 966940M] ########## FTL started! ##########
[2020-11-29 10:14:14.977 966940M] FTL branch: master
[2020-11-29 10:14:14.977 966940M] FTL version: v5.2
[2020-11-29 10:14:14.977 966940M] FTL commit: dbd4a69
[2020-11-29 10:14:14.977 966940M] FTL date: 2020-08-09 22:09:43 +0100
[2020-11-29 10:14:14.978 966940M] FTL user: root
[2020-11-29 10:14:14.978 966940M] Compiled for x86_64 (compiled on CI) using gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
[2020-11-29 10:14:14.978 966940M] Starting config file parsing (/etc/pihole/pihole-FTL.conf)
[2020-11-29 10:14:14.978 966940M]    SOCKET_LISTENING: only local
[2020-11-29 10:14:14.978 966940M]    AAAA_QUERY_ANALYSIS: Show AAAA queries
[2020-11-29 10:14:14.978 966940M]    MAXDBDAYS: max age for stored queries is 365 days
[2020-11-29 10:14:14.978 966940M]    RESOLVE_IPV6: Resolve IPv6 addresses
[2020-11-29 10:14:14.979 966940M]    RESOLVE_IPV4: Resolve IPv4 addresses
[2020-11-29 10:14:14.979 966940M]    DBINTERVAL: saving to DB file every minute
[2020-11-29 10:14:14.979 966940M]    DBFILE: Using /etc/pihole/pihole-FTL.db
[2020-11-29 10:14:14.979 966940M]    MAXLOGAGE: Importing up to 24.0 hours of log data
[2020-11-29 10:14:14.979 966940M]    PRIVACYLEVEL: Set to 0
[2020-11-29 10:14:14.979 966940M]    IGNORE_LOCALHOST: Show queries from localhost
[2020-11-29 10:14:14.979 966940M]    BLOCKINGMODE: Null IPs for blocked domains
[2020-11-29 10:14:14.979 966940M]    ANALYZE_ONLY_A_AND_AAAA: Disabled. Analyzing all queries
[2020-11-29 10:14:14.980 966940M]    DBIMPORT: Importing history from database
[2020-11-29 10:14:14.980 966940M]    PIDFILE: Using /run/pihole-FTL.pid
[2020-11-29 10:14:14.980 966940M]    PORTFILE: Using /run/pihole-FTL.port
[2020-11-29 10:14:14.980 966940M]    SOCKETFILE: Using /run/pihole/FTL.sock
[2020-11-29 10:14:14.980 966940M]    SETUPVARSFILE: Using /etc/pihole/setupVars.conf
[2020-11-29 10:14:14.980 966940M]    MACVENDORDB: Using /etc/pihole/macvendor.db
[2020-11-29 10:14:14.980 966940M]    GRAVITYDB: Using /etc/pihole/gravity.db
[2020-11-29 10:14:14.981 966940M]    PARSE_ARP_CACHE: Active
[2020-11-29 10:14:14.981 966940M]    CNAME_DEEP_INSPECT: Active
[2020-11-29 10:14:14.981 966940M]    DELAY_STARTUP: No delay requested.
[2020-11-29 10:14:14.981 966940M]    NICE: Set process niceness to -10 (default)
[2020-11-29 10:14:14.981 966940M]    BLOCK_ESNI: Enabled, blocking _esni.{blocked domain}
[2020-11-29 10:14:14.981 966940M]    NAMES_FROM_NETDB: Enabled, trying to get names from network database
[2020-11-29 10:14:14.981 966940M] Finished config file parsing
[2020-11-29 10:14:14.982 966940M] WARNING: Starting pihole-FTL as user root is not recommended
[2020-11-29 10:14:14.985 966940M] Database version is 7
[2020-11-29 10:14:14.985 966940M] Database successfully initialized
[2020-11-29 10:14:14.986 966940M] New upstream server: xxx.xxx.xxx.xxx (0/128)
[2020-11-29 10:14:14.996 966940M] Resizing "/FTL-queries" from 262144 to 524288
[2020-11-29 10:14:14.998 966940M] New upstream server: xxx.xxx.xxx.xxx (1/128)
[2020-11-29 10:14:15.001 966940M] Resizing "/FTL-strings" from 4096 to 8192
[2020-11-29 10:14:15.008 966940M] Resizing "/FTL-queries" from 524288 to 786432
[2020-11-29 10:14:15.014 966940M] Imported 9716 queries from the long-term database
[2020-11-29 10:14:15.015 966940M]  -> Total DNS queries: 9716
[2020-11-29 10:14:15.015 966940M]  -> Cached DNS queries: 7959
[2020-11-29 10:14:15.015 966940M]  -> Forwarded DNS queries: 1646
[2020-11-29 10:14:15.015 966940M]  -> Blocked DNS queries: 111
[2020-11-29 10:14:15.015 966940M]  -> Unknown DNS queries: 0
[2020-11-29 10:14:15.015 966940M]  -> Unique domains: 320
[2020-11-29 10:14:15.015 966940M]  -> Unique clients: 9
[2020-11-29 10:14:15.015 966940M]  -> Known forward destinations: 2
[2020-11-29 10:14:15.016 966940M] Successfully accessed setupVars.conf
[2020-11-29 10:14:15.023 966940M] PID of FTL process: 966940
[2020-11-29 10:14:15.024 966940/T966944] Listening on port 4711 for incoming IPv4 telnet connections
[2020-11-29 10:14:15.025 966940/T966946] Listening on Unix socket
[2020-11-29 10:14:15.025 966940/T966945] Listening on port 4711 for incoming IPv6 telnet connections
[2020-11-29 10:14:15.026 966940M] Changing /FTL-lock (15) to 0:0
[2020-11-29 10:14:15.026 966940M] Changing /FTL-strings (15) to 0:0
[2020-11-29 10:14:15.026 966940M] Changing /FTL-counters (15) to 0:0
[2020-11-29 10:14:15.026 966940M] Changing /FTL-domains (15) to 0:0
[2020-11-29 10:14:15.027 966940M] Changing /FTL-clients (15) to 0:0
[2020-11-29 10:14:15.027 966940M] Changing /FTL-queries (15) to 0:0
[2020-11-29 10:14:15.027 966940M] Changing /FTL-upstreams (15) to 0:0
[2020-11-29 10:14:15.027 966940M] Changing /FTL-overTime (15) to 0:0
[2020-11-29 10:14:15.027 966940M] Changing /FTL-settings (15) to 0:0
[2020-11-29 10:14:15.027 966940M] Changing /FTL-dns-cache (15) to 0:0
[2020-11-29 10:14:15.027 966940M] Changing /FTL-per-client-regex (15) to 0:0

so the diff is the following lines
 New upstream server: xxx.xxx.xxx.xxx (0/128)
in the new version its not loading it.
and then trying to resolv something just gives a timeout
REgards
Filip

**Comment by DL6ER** [comment]
These issues seem to be two independent ones.

@jasonbayton 

> Pinhole-ftl tells me the address is already in use in both VMs
> 53 is listed in netstat with no process assigned to it

Maybe `systemd-resolved` grabbed the port. If it is taken, Pi-hole cannot start its `pihole-FTL` daemon.

@FilipFrancis 

> so the diff is the following lines
> New upstream server: xxx.xxx.xxx.xxx (0/128)
> in the new version its not loading it.

This line just shows that a new server has been used to request. Its absence doesn't automatically means it isn't aware of it. You should rather compare `/var/log/pihole.log` where the actually used DNS servers are logged like:
> ```
> Nov 28 23:25:25 dnsmasq[25662]: using nameserver 127.0.0.1#5353
> ```

**Comment by FilipFrancis** [comment]
When i do /etc/rc2.d/S50pihole-FTL status i go this
[    ] pihole-FTL is not running
so to start
/etc/rc2.d/S50pihole-FTL start
FTL started
to check
/etc/rc2.d/S50pihole-FTL status
[ ok ] pihole-FTL is running
netstat -an |grep 53
tcp        0      0 0.0.0.0:53              0.0.0.0:*               LISTEN     
tcp6       0      0 :::53                   :::*                    LISTEN     
udp        0      0 0.0.0.0:53              0.0.0.0:*                          
udp6       0      0 :::53                   :::*       
and doing dig @127.0.0.1 www.hp.com give me this result
dig @127.0.0.1 www.hp.com

; <<>> DiG 9.11.4-P2-RedHat-9.11.4-26.P2.el7_9.2 <<>> @127.0.0.1 www.hp.com
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached

So that used to be working before the upgrade and even with new install getting timeout
Also the webinterface is so slow  beofre upgrade working fine
So something is off
and is till ebleive it has something to do with not adding the dns severs in his list

**Comment by DL6ER** [comment]
So what does `/var/log/pihole.log` contain?

**Comment by FilipFrancis** [comment]
Nov 29 16:44:40 dnsmasq[896]: started, version pi-hole-2.81 cachesize 10000
Nov 29 16:44:40 dnsmasq[896]: compile time options: IPv6 GNU-getopt no-DBus no-UBus no-i18n IDN DHCP DHCP
v6 Lua TFTP no-conntrack ipset auth DNSSEC loop-detect inotify dumpfile
Nov 29 16:44:40 dnsmasq[896]: using only locally-known addresses for domain use-application-dns.net
Nov 29 16:44:40 dnsmasq[896]: using nameserver 8.8.4.4#53
Nov 29 16:44:40 dnsmasq[896]: using nameserver 8.8.8.8#53
Nov 29 16:44:40 dnsmasq[896]: read /etc/hosts - 3 addresses
Nov 29 16:44:40 dnsmasq[896]: read /etc/pihole/custom.list - 0 addresses
Nov 29 16:44:40 dnsmasq[896]: failed to load names from /etc/pihole/local.list: No such file or directory
[root@piholednstest log]# tail -f pihole.log 
Nov 29 16:44:40 dnsmasq[896]: started, version pi-hole-2.81 cachesize 10000
Nov 29 16:44:40 dnsmasq[896]: compile time options: IPv6 GNU-getopt no-DBus no-UBus no-i18n IDN DHCP DHCPv6 Lua TFTP no-conntrack ipset auth DNSSEC loop-detect inotify dumpfile
Nov 29 16:44:40 dnsmasq[896]: using only locally-known addresses for domain use-application-dns.net
Nov 29 16:44:40 dnsmasq[896]: using nameserver 8.8.4.4#53
Nov 29 16:44:40 dnsmasq[896]: using nameserver 8.8.8.8#53
Nov 29 16:44:40 dnsmasq[896]: read /etc/hosts - 3 addresses
Nov 29 16:44:40 dnsmasq[896]: read /etc/pihole/custom.list - 0 addresses
Nov 29 16:44:40 dnsmasq[896]: failed to load names from /etc/pihole/local.list: No such file or directory
Nov 29 16:45:25 dnsmasq[896]: query[A] www.hp.com from 192.168.90.29
Nov 29 16:45:25 dnsmasq[896]: netlink returns error: Unknown error -122

**Comment by jasonbayton** [comment]
> Maybe systemd-resolved grabbed the port. If it is taken, Pi-hole cannot start its pihole-FTL daemon.

systemd-resolved is not running. I'm not seeing anything else that might be trying to take it. 5.1.2 didn't have this problem before upgrading, and handled reboots and such that'd have offered ample opportunity for something else to take 53 before upgrading but this didn't happen.

**Comment by khoitan2704** [comment]
pod "youtube-ios-player-helper", "~> x.y.z"

**Comment by FilipFrancis** [comment]
systemd-resolved is not running on the old system either
but when doing just dig www.hp.com  its using the correct resolver which is an other one in my network
But should  dnsmasq not send the address to a resolv address that is being added  via the web interface
so if you add in the web interface  8.8.4.4 it should use that one  in my cas my internal dns server where my clients are configred and that can also resolv the internet address thats the way its working on the old pihole servers 
but once upgrading its not working any more

**Comment by DL6ER** [comment]
@FilipFrancis 
```
Nov 29 16:44:40 dnsmasq[896]: using nameserver 8.8.4.4#53
Nov 29 16:44:40 dnsmasq[896]: using nameserver 8.8.8.8#53
```
shows it's aware of Google's DNS servers.
```
Nov 29 16:45:25 dnsmasq[896]: query[A] www.hp.com from 192.168.90.29
Nov 29 16:45:25 dnsmasq[896]: netlink returns error: Unknown error -122
```
This netlink error is something I have never seen before and don't know how to resolve. You're the first one reporting this and may be able to get some more help on the `dnsmasq` mailing list: http://lists.thekelleys.org.uk/mailman/listinfo/dnsmasq-discuss

---

@jasonbayton Okay, so it doesn't seem like someone else is taking the port. Can you quote some relevant lines from `/var/log/pihole.log` as well?

**Comment by FilipFrancis** [comment]
Here you have the complete log
[pihole.log](https://github.com/pi-hole/pi-hole/files/5612541/pihole.log)

**Comment by jasonbayton** [comment]
Here's some of my pihole-ftl log:

`[2020-11-29 18:08:16.531 1172M] Database version is 9
[2020-11-29 18:08:16.531 1172M] Imported 0 alias-clients
[2020-11-29 18:08:16.531 1172M] Database successfully initialized
[2020-11-29 18:08:16.532 1172M] New upstream server: 8.8.4.4:53 (0/512)            [2020-11-29 18:08:16.532 1172M] New upstream server: 8.8.8.8:53 (1/512)
[2020-11-29 18:08:16.533 1172M] Imported 330 queries from the long-term database
[2020-11-29 18:08:16.533 1172M]  -> Total DNS queries: 330
[2020-11-29 18:08:16.533 1172M]  -> Cached DNS queries: 116
[2020-11-29 18:08:16.533 1172M]  -> Forwarded DNS queries: 212
[2020-11-29 18:08:16.533 1172M]  -> Blocked DNS queries: 2
[2020-11-29 18:08:16.533 1172M]  -> Unknown DNS queries: 0
[2020-11-29 18:08:16.533 1172M]  -> Unique domains: 27                             [2020-11-29 18:08:16.533 1172M]  -> Unique clients: 2
[2020-11-29 18:08:16.533 1172M]  -> Known forward destinations: 2
[2020-11-29 18:08:16.533 1172M] Successfully accessed setupVars.conf
[2020-11-29 18:08:16.534 1172M] FATAL ERROR in dnsmasq core: failed to create listening socket for port 53: Address already in use`

And pihole.log from a FTL service restart 

`Nov 29 18:05:23 dnsmasq[351]: exiting on receipt of SIGTERM
Nov 29 18:05:23 dnsmasq[1090]: started, version pi-hole-2.81 cachesize 10000       Nov 29 18:05:23 dnsmasq[1090]: compile time options: IPv6 GNU-getopt no-DBus no-UBus no-i18n IDN DHCP DHCPv6 Lua TFTP no-conntrack ipset auth DNSSEC loop-detect inotify dumpfile
Nov 29 18:05:23 dnsmasq[1090]: using only locally-known addresses for domain use-application-dns.net
Nov 29 18:05:23 dnsmasq[1090]: using nameserver 8.8.4.4#53
Nov 29 18:05:23 dnsmasq[1090]: using nameserver 8.8.8.8#53
Nov 29 18:05:23 dnsmasq[1090]: read /etc/hosts - 7 addresses
Nov 29 18:05:23 dnsmasq[1090]: read /etc/pihole/custom.list - 0 addresses
Nov 29 18:05:23 dnsmasq[1090]: read /etc/pihole/local.list - 2 addresses
Nov 29 18:06:00 dnsmasq[1090]: query[PTR] 4.4.8.8.in-addr.arpa from 127.0.0.1
Nov 29 18:06:00 dnsmasq[1090]: forwarded 4.4.8.8.in-addr.arpa to 8.8.4.4
Nov 29 18:06:00 dnsmasq[1090]: forwarded 4.4.8.8.in-addr.arpa to 8.8.8.8
Nov 29 18:06:00 dnsmasq[1090]: reply 8.8.4.4 is dns.google
Nov 29 18:06:00 dnsmasq[1090]: query[PTR] 8.8.8.8.in-addr.arpa from 127.0.0.1
Nov 29 18:06:00 dnsmasq[1090]: forwarded 8.8.8.8.in-addr.arpa to 8.8.4.4           Nov 29 18:06:00 dnsmasq[1090]: reply 8.8.8.8 is dns.google                         Nov 29 18:08:12 dnsmasq[1090]: exiting on receipt of SIGTERM
Nov 29 18:08:12 dnsmasq[1165]: started, version pi-hole-2.81 cachesize 10000       Nov 29 18:08:12 dnsmasq[1165]: compile time options: IPv6 GNU-getopt no-DBus no-UBus no-i18n IDN DHCP DHCPv6 Lua TFTP no-conntrack ipset auth DNSSEC loop-detect inotify dumpfile
Nov 29 18:08:12 dnsmasq[1165]: using only locally-known addresses for domain use-application-dns.net
Nov 29 18:08:12 dnsmasq[1165]: using nameserver 8.8.4.4#53
Nov 29 18:08:12 dnsmasq[1165]: using nameserver 8.8.8.8#53
Nov 29 18:08:12 dnsmasq[1165]: read /etc/hosts - 7 addresses
Nov 29 18:08:12 dnsmasq[1165]: read /etc/pihole/custom.list - 0 addresses
Nov 29 18:08:12 dnsmasq[1165]: read /etc/pihole/local.list - 2 addresses
Nov 29 18:09:00 dnsmasq[1165]: query[PTR] 4.4.8.8.in-addr.arpa from 127.0.0.1
Nov 29 18:09:00 dnsmasq[1165]: forwarded 4.4.8.8.in-addr.arpa to 8.8.4.4
Nov 29 18:09:00 dnsmasq[1165]: forwarded 4.4.8.8.in-addr.arpa to 8.8.8.8
Nov 29 18:09:00 dnsmasq[1165]: reply 8.8.4.4 is dns.google
Nov 29 18:09:00 dnsmasq[1165]: query[PTR] 8.8.8.8.in-addr.arpa from 127.0.0.1
Nov 29 18:09:00 dnsmasq[1165]: forwarded 8.8.8.8.in-addr.arpa to 8.8.8.8
Nov 29 18:09:00 dnsmasq[1165]: reply 8.8.8.8 is dns.google`

**Comment by sadsfae** [comment]
I ran into this issue as well on CentOS8, turns out `lsof` was needed now in 5.2 for part of how the DNS service advertises itself as listening or not in both the web UI and process check (but it is indeed working).  

https://github.com/pi-hole/pi-hole/blob/master/pihole#L284

```
# pihole status
/usr/local/bin/pihole: line 284: lsof: command not found
[✗] DNS service is NOT listening
```

After installing `lsof` DNS was reported as working again in both the UI and service status.  There should be a check for `lsof` as a package dependency as it's not present in all distributions out of the box and seems to be required for now in ways that display DNS service status.

**Comment by yubiuser** [comment]
> There should be a check for lsof as a package dependency as it's not present in all distributions out of the box and seems to be required for now in ways that display DNS service status.

This is already fixed by https://github.com/pi-hole/pi-hole/pull/3877

**Comment by sadsfae** [comment]
> > There should be a check for lsof as a package dependency as it's not present in all distributions out of the box and seems to be required for now in ways that display DNS service status.
> 
> This is already fixed by #3877

That's great, I guess it wasn't in place when I ran into the issue above but glad it's fixed.  Thanks folks.

**Comment by PromoFaux** [comment]
Just to clarify, it is still yet to be released (5.2.1 should™ be coming in the next day or so), but it is fixed in development

**Comment by PromoFaux** [comment]
Fixed in 5.2.1

**Comment by jasonbayton** [comment]
The update has not resolved this for me.

**Comment by x-jokay** [comment]
Still a problem using `pihole/pihole:latest` for me as well, this issue should be reopened.

```sh
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-resolver-resolv: applying... 
[fix-attrs.d] 01-resolver-resolv: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 20-start.sh: executing... 
 ::: Starting docker specific checks & setup for docker pihole/pihole
  [✓] Update local cache of available packages
  [i] Existing PHP installation detected : PHP version 7.3.19-1~deb10u1

  [i] Installing configs from /etc/.pihole...
  [i] Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!
  [✓] Copying 01-pihole.conf to /etc/dnsmasq.d/01-pihole.conf
chown: cannot access '': No such file or directory
chmod: cannot access '': No such file or directory
chown: cannot access '/etc/pihole/dhcp.leases': No such file or directory
::: Pre existing WEBPASSWORD found
Using custom DNS servers: 127.0.0.1 & 9.9.9.9
DNSMasq binding to default interface: eth0
Added ENV to php:
			"PHP_ERROR_LOG" => "/var/log/lighttpd/error.log",
			"ServerIP" => "192.168.1.123",
			"VIRTUAL_HOST" => "pihole.sample.com",
Using IPv4
::: Preexisting ad list /etc/pihole/adlists.list detected ((exiting setup_blocklists early))
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
https://mirror1.malwaredomains.com/files/justdomains
https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
::: Testing pihole-FTL DNS: FTL started!
::: Testing lighttpd config: Syntax OK
::: All config checks passed, cleared for startup ...
 ::: Docker start setup complete
  [i] Neutrino emissions detected...
  [✓] Pulling blocklist source list into range

  [✓] Preparing new gravity database
  [i] Using libz compression

  [i] Target: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  [✓] Status: Retrieval successful
  [i] Received 58230 domains

  [i] Target: https://mirror1.malwaredomains.com/files/justdomains
  [✓] Status: Retrieval successful
  [i] Received 26854 domains

  [i] Target: https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
  [✓] Status: No changes detected
  [i] Received 2701 domains

  [i] Target: https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
  [✓] Status: Retrieval successful
  [i] Received 2701 domains

  [✓] Storing downloaded domains in new gravity database
  [✓] Building tree
  [✓] Swapping databases
  [i] Number of gravity domains: 90486 (85653 unique domains)
  [i] Number of exact blacklisted domains: 0
  [i] Number of regex blacklist filters: 0
  [i] Number of exact whitelisted domains: 0
  [i] Number of regex whitelist filters: 0
  [✓] Cleaning up stray matter

  [✗] DNS service is NOT listening
  Pi-hole version is v5.2.1 (Latest: v5.2.1)
  AdminLTE version is v5.2.1 (Latest: v5.2.1)
  FTL version is v5.3.2 (Latest: v5.3.2)
[cont-init.d] 20-start.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
Starting lighttpd
Starting pihole-FTL (no-daemon) as pihole
[services.d] done.
Starting crond
```

`[✗] DNS service is NOT listening`

**Comment by PromoFaux** [comment]
@x-jokay, as you're using docker image (which I know works) it is likely a configuration issue. What does your compose file/run script look like?

**Comment by x-jokay** [comment]
@PromoFaux Yes, it was working using `5.1.2` but after the upgrade to `5.2.1` no more.

This is how the `docker-compose.yml` looks like:

```yml
pihole:
  image: pihole/pihole:v5.2.1
  volumes:
    - ./data:/etc/pihole
  ports:
    - 53:53
    - 53:53/udp
    - 8080:80
  environment:
    - ServerIP=192.168.1.123
    - VIRTUAL_HOST=pihole.sample.com
    - WEBPASSWORD=***
    - DNS1=127.0.0.1
    - DNS2=9.9.9.9
    - IPv6=true
    - DNSSEC=true
    - DNSMASQ_USER=pihole
```

May be some upgrade problems in combination with the persistent data folder `/etc/pihole`.

**Comment by x-jokay** [comment]
This is the startup log if `./data:/etc/pihole` is empty:

```sh
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-resolver-resolv: applying... 
[fix-attrs.d] 01-resolver-resolv: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 20-start.sh: executing... 
 ::: Starting docker specific checks & setup for docker pihole/pihole
  [✓] Update local cache of available packages
  [i] Existing PHP installation detected : PHP version 7.3.19-1~deb10u1

  [i] Installing configs from /etc/.pihole...
  [i] Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!
  [✓] Copying 01-pihole.conf to /etc/dnsmasq.d/01-pihole.conf
chown: cannot access '': No such file or directory
chmod: cannot access '': No such file or directory
chown: cannot access '/etc/pihole/dhcp.leases': No such file or directory
Setting password: ***
+ pihole -a -p *** ***
  [✓] New password set
Using custom DNS servers: 127.0.0.1 & 9.9.9.9
DNSMasq binding to default interface: eth0
Added ENV to php:
			"PHP_ERROR_LOG" => "/var/log/lighttpd/error.log",
			"ServerIP" => "192.168.1.123",
			"VIRTUAL_HOST" => "pihole.sample.com",
Using IPv4
::: setup_blocklists now setting default blocklists up: 
::: TIP: Use a docker volume for /etc/pihole/adlists.list if you want to customize for first boot
::: Blocklists (/etc/pihole/adlists.list) now set to:
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
https://mirror1.malwaredomains.com/files/justdomains
::: Testing pihole-FTL DNS: FTL started!
::: Testing lighttpd config: Syntax OK
::: All config checks passed, cleared for startup ...
 ::: Docker start setup complete
  [i] Neutrino emissions detected...
  [✓] Pulling blocklist source list into range

  [✓] Preparing new gravity database
  [i] Using libz compression

  [i] Target: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  [✓] Status: Retrieval successful
  [i] Received 58230 domains

  [i] Target: https://mirror1.malwaredomains.com/files/justdomains
  [✓] Status: No changes detected
  [i] Received 26854 domains

  [✓] Storing downloaded domains in new gravity database
  [✓] Building tree
  [✓] Swapping databases
  [i] Number of gravity domains: 85084 (85053 unique domains)
  [i] Number of exact blacklisted domains: 0
  [i] Number of regex blacklist filters: 0
  [i] Number of exact whitelisted domains: 0
  [i] Number of regex whitelist filters: 0
  [✓] Cleaning up stray matter

  [✗] DNS service is NOT listening
  Pi-hole version is v5.2.1 (Latest: v5.2.1)
  AdminLTE version is v5.2.1 (Latest: v5.2.1)
  FTL version is v5.3.2 (Latest: v5.3.2)
[cont-init.d] 20-start.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
Starting lighttpd
Starting pihole-FTL (no-daemon) as pihole
Starting crond
[services.d] done.
```

**Comment by x-jokay** [comment]
Seems to be a permisson problem (at least for me).

When not using `DNSMASQ_USER` it works:

```yml
environment: 
  - DNSMASQ_USER=pihole
```

**Comment by PromoFaux** [comment]
As I said, I think what you are seeing is a different issue - I'm going to hid the above few comments as they are to do with the docker image (and possibly configuration.

**Comment by rvs007** [comment]
I'm running into the same issue with my pi-hole set up on a Rpi4 alongside Homebridge.  It has been working fine up to a few days ago, but then something went wrong with Homebridge which took down Pi-Hole (in that I no longer could access the Web UI).  I restored homebridge's configure and also did a reinstall of Pi-Hole after I got HB back on its feet.  After I reinstalled Pihole the DNS server would not listen, and on the status, it says "DNS Service not running".  But I can see Pi-hole is still working and blocking.

**Comment by TroglodyteGuy** [comment]
I am having the same issue today. I updated my OS (sudo apt update; sudo apt full-upgrade). Restarted RPi (3B+) and Pi-hole will not come back up. I see this in the FTL log:

FATAL ERROR in dnsmasq core: failed to create listening socket for port 53: Address already in use

Seems something is grabbing port 53, but not sure what. This is a grep of port details:

sudo netstat -nltup | grep 'Proto\|:53 \|:67 \|:80 \|:471'
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:4711          0.0.0.0:*               LISTEN      682/pihole-FTL
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      620/lighttpd
tcp        0      0 0.0.0.0:53              0.0.0.0:*               LISTEN      682/pihole-FTL
tcp6       0      0 ::1:4711                :::*                    LISTEN      682/pihole-FTL
tcp6       0      0 :::80                   :::*                    LISTEN      620/lighttpd
tcp6       0      0 :::53                   :::*                    LISTEN      682/pihole-FTL
udp        0      0 0.0.0.0:53              0.0.0.0:*                           682/pihole-FTL
udp6       0      0 :::53                   :::*                                682/pihole-FTL

Not sure where else to look to resolve. Suggestions for next steps?
