### ISSUE TITLE
After update to 2.6.1.2, /etc/crontab still list "old" commands

### ISSUE THREAD

**Issue by nagubal** [pi-hole/pi-hole#446]
Hello, 
I have been using the Pi-Hole for a few months with great success (many thanks!).

Today, I noticed that the /etc/crontab still lists the "old" commands:

```
pi@pi-hole:~ $ more /etc/crontab
[...]

# Pi-hole: Update the ad sources once a week on Sunday at 01:59
#          Download any updates from the ad lists
59 1    * * 7   root    /usr/local/bin/gravity.sh

# Pi-hole: Parse the log file before it is flushed and save the stats to a database
#          This will be used for a historical view of your Pi-hole's performance
#50 11  * * *   root    /usr/local/bin/dailyLog.sh

# Pi-hole: Flush the log daily at 11:58 so it doesn't get out of control
#          Stats will be viewable in the Web interface thanks to the cron job above
58 11   * * *   root    /usr/local/bin/piholeLogFlush.sh
```
Of course the `/usr/local/bin/piholeLogFlush.sh` command fails because the file does not exist anymore.

I also have the new `/etc/cron.d/pihole` file which has the new commands.

I suppose it is safe to remove the "old" commands from the /etc/crontab ?

Thanks

**Comment by Mcat12** [comment]
I think this was fixed with a quick update. Can you update and check? `curl -L https://install.pi-hole.net | bash`

**Comment by nagubal** [comment]
Hi, I just re-updated with `curl -L https://install.pi-hole.net | bash` but the `/etc/crontab`is still the same.
No much of an issue, I can clean up the /etc/crontab by myself...

**Comment by Mcat12** [comment]
Oh, we install the cron to `/etc/cron.d/pihole`

**Comment by PromoFaux** [comment]
What is it that populates crontab?

**Comment by PromoFaux** [comment]
But yes,  more than safe to remove. The jobs in the `cron.d` directory run

**Comment by nagubal** [comment]
It must from a previous PI-Hole install: the last modified date was January 3rd (pi-hole version 2.2 I guess).
I removed the old jobs.
Thanks.
