### ISSUE TITLE
Pi-hole does not make it clear that Whitelist is associated to group(s)

### ISSUE THREAD

**Issue by ronald-mendoza** [pi-hole/pi-hole#4581]
### Versions
- Pi-hole:  v5.8.1
- AdminLTE:  v5.10.1
- FTL:  v5.13

### Platform
- OS and version:  Ubuntu 21.10
- Platform:  bare metal

### Expected behavior

Both at the console, as well as in the web GUI, it is not clear that the **Whitelist** entries are actually associated with a group. (The _Default_ group that is created after install.) Because of this, it is very easy to assume that the Whitelist entries are global.
The documentation should be clear that the Whitelist function adds an entry to **Group Management** > **Domains**, assigned to the _Default_ group, and that it needs to be adjusted if that is not the intended behavior.
In addition, I would suggest that any viewing of the Whitelist should also include the group assignment.
e.g. at the console, using `pihole -w -l` should also include the group(s) that each domain is assigned to
in the web GUI, the section of the Whitelist page that shows a table for the List of whitelisted entries should include a column for the group(s) each Domain/RegEx is assigned to -OR- instead of showing a List of whitelisted entries, it should point the user to **Group Management** > **Domains**.

### Actual behavior / bug

Because the **Whitelist** entries are assigned to the _Default_ group, if you have any additional groups created, and have adlist(s) associated with those groups, adding entries to the Whitelist will not apply to the non-Default group(s). This gives the impression that the Whitelist is not functioning.

### Steps to reproduce

Add a non-default group. Assign an adlist to that non-default group. Add a Whitelist entry at the console or in the web GUI. Test using a client that belongs to the non-default group and confirm that the whitelisted entry is not effective.
Next, in the web GUI, go to **Group Management** > **Domains**. Find the domain related to the whitelist entry, and notice that it actually has a group assignment to the Default group.
Assign that domain to the non-default group and re-test, to confirm that the whitelisted entry is now effective.

**Comment by ronald-mendoza** [comment]
@PromoFaux Can you elaborate on what documentation would be needed?

**Comment by PromoFaux** [comment]
> The documentation should be clear that the Whitelist function adds an entry to Group Management > Domains, assigned to the Default group, and that it needs to be adjusted if that is not the intended behavior.

This, no? The label is more of a reminder that we need to look at the documentation (and/or anyone else that wants to document it and submit a PR)

**Comment by ronald-mendoza** [comment]
Gotcha. I thought the label meant that the team needed more documentation **from me** to understand what I was reporting.

Besides updating the documentation, I had also made a suggestion on product changes at the console and the GUI, to more clearly reflect the group(s) assigned with any domain on the whitelist.

**Comment by martinbrose** [comment]
@PromoFaux I have given this a go and filed two related PRs in pi-hole/docs and pi-hole/AdminLTE.

At least that should address the documentation request from @ronald-mendoza.

Adding the associated groups to the output of `pihole -w -l` would require changes in pi-hole/FTL?
I guess the terminal output could get quite messy quickly, so not sure if this is agreed to be looked at?

**Comment by rdwebdesign** [comment]
I think this issue was addressed months ago, but never closed.

Currently, there is a **note** explicitly saying the domain/regex will be added to the _Default Group_:
![image](https://user-images.githubusercontent.com/1385443/196267454-afa7bca0-e72c-425c-84ac-f05fd0c9983e.png)

Also, the documentation was updated.

Can we close this?

**Comment by ronald-mendoza** [comment]
I think the note in the WebUI is sufficient. But what about at the console?

`pihole -w -l` still does not show any group association with entries, and I'm not even sure it is possible to assign a non-default group to an entry at the command-line.

**Comment by yubiuser** [comment]
> `pihole -w -l` still does not show any group association with entries

This is true. We could, however, change the current `pihole -w -l` code to the output we have in `pihole -d` "Domainlist" and just filter for white/blacklist entries.

>  I'm not even sure it is possible to assign a non-default group to an entry at the command-line.

Not with a `pihole` command. The web interface executes `sqlite` commands directly to modify the group assignment. You could do the same.

**Comment by begunfx** [comment]
Can we please adjust the Group Assignment behavior for domains so if we want to create custom Group Assignments (ie. whitelist/blacklist etc.) they are honored?  I tried to add several sites to a custom "whitelist" Group assignment and it seemed like they didn't whitelist until I reassigned them to the default group.  This seems to be what was discussed previously in this thread the focus was on documentation.

**Comment by yubiuser** [comment]
When you assign them to a custom group, they only apply to that specific group. If you assign them to the default group they apply to all clients not configured otherwise.

**Comment by begunfx** [comment]
> When you assign them to a custom group, they only apply to that specific group. If you assign them to the default group they apply to all clients not configured otherwise.

Okay.  Then I guess I misunderstood how groups work.  Thank your for the clarification.

**Comment by begunfx** [comment]
> It can be tricky to understand how they work. Have a look here for some nice examples
> 
> https://docs.pi-hole.net/group_management/example/

Awesome.  Thank you.
