### ISSUE TITLE
Latest update makes my pihole look itself up constantly

### ISSUE THREAD

**Issue by trathborne** [pi-hole/pi-hole#4613]
### Versions
  Pi-hole version is v5.9 (Latest: v5.9)
  AdminLTE version is v5.11 (Latest: v5.11)
  FTL version is v5.14 (Latest: v5.14)

I keep my pihole up to date so I was previously using whatever was latest. This problem started immediately after my latest `pihole -up`.

### Platform
- OS and version:  Raspbian GNU/Linux 11
- Platform:  Raspberry Pi 3B

### Expected behavior

Pi hole doesn't constantly look itself up

### Actual behavior / bug

Watching the admin webpage, the lookup count goes up by ~2/s even when nothing else on the network is particularly active. The graph shows 'pi.kpn' as the top client. That's the hostname of this pihole; .kpn is the local isp-router-provided domain. The router is my first upstream DNS server. The query log shows that pi.kpn is repeatedly looking up `A pi.kpn` at about the rate shown in the admin page.

### Steps to reproduce

1. Upgrade to latest versions noted above
2. Observe that the pi is constantly looking itself up

## Debug Token

- URL:  https://tricorder.pi-hole.net/flMHptP1/

**Comment by trathborne** [comment]
Oh! I also tried adding pi.kpn to /etc/hosts and the FTL DNS, and rebooting, and it's still doing this.

**Comment by yubiuser** [comment]
Please run `pihole -t` and watch if the queries are also arriving if you are not using the dashboard at the same time.

**Comment by yubiuser** [comment]
Cross post, likely the same issue: https://discourse.pi-hole.net/t/a-lot-of-queries-while-viewing-the-dashboard/53570

**Comment by trathborne** [comment]
Yep, pihole -t only shows these queries when I have the dashboard open.

**Comment by trathborne** [comment]
... happens with latest Chrome and Firefox.

**Comment by rdwebdesign** [comment]
Just to be sure:
Do you see this behavior in every dashboard page or just the initial page (`index.php`)?

**Comment by billvinson** [comment]
I seem to be having the same issue.
I see the volume of self lookups on the index page, but I also see the individual requests on http://pi.hole:8080/admin/queries.php. However, if I click on pi.hole under the 'Top Clients', I get a 500 error accessing api.php on this page: http://pi.hole:8080/admin/queries.php?client=10.10.10.175

Not sure if it helps, but I wanted to provide the details I've been looking at.

**Comment by trathborne** [comment]
@rdwebdesign ... still 2 requests per second in that case.

If I open 3 tabs (to the hostname or IP) then it's ~6 per second.

Same as if I `while true; do curl http://pi/admin/api.php?summaryRaw ; sleep 1; done` so ... it looks like something in api.php is triggering these lookups.

**Comment by yubiuser** [comment]
What's the output of `/etc/hosts`?

**Comment by trathborne** [comment]
/etc/hosts:
```
127.0.0.1       localhost
::1             localhost ip6-localhost ip6-loopback
ff02::1         ip6-allnodes
ff02::2         ip6-allrouters

127.0.1.1       raspberrypi
192.168.2.199   pi.kpn
```

I added `pi.kpn` in an attempt to stop the lookups, but it didn't help and nothing changes when I remove it.

**Comment by trathborne** [comment]
Tried that, didn't help. I even included ::1 in hopes of catching AAAA lookups.

**Comment by ezek1el** [comment]
I can confirm the behavior. Takes place only on index.php.

**Comment by plumped** [comment]
Same here experienced today at latest version

**Comment by djrm05** [comment]
> /etc/hosts:
> 
> ```
> 127.0.0.1       localhost
> ::1             localhost ip6-localhost ip6-loopback
> ff02::1         ip6-allnodes
> ff02::2         ip6-allrouters
> 
> 127.0.1.1       raspberrypi
> 192.168.2.199   pi.kpn
> ```
> 
> I added `pi.kpn` in an attempt to stop the lookups, but it didn't help and nothing changes when I remove it.

Try to add this entry to the top of hosts file (need to be the first one in the list). This worked for me some time ago.....

**Comment by trathborne** [comment]
> > I added pi.kpn in an attempt to stop the lookups, but it didn't help and nothing changes when I remove it.
> 
> Try to add this entry to the top of hosts file (need to be the first one in the list). This worked for me some time ago.....

Thanks for the suggestion. Didn't help over here. My solution has been to only open the pihole page when I want to look at it instead of keeping it open in a pinned tab. ☺

**Comment by hagnard** [comment]
> > > I added pi.kpn in an attempt to stop the lookups, but it didn't help and nothing changes when I remove it.
> > 
> > 
> > Try to add this entry to the top of hosts file (need to be the first one in the list). This worked for me some time ago.....
> 
> Thanks for the suggestion. Didn't help over here. My solution has been to only open the pihole page when I want to look at it instead of keeping it open in a pinned tab. relaxed

Have you tried changing the address of it to 127.0.0.1 instead? I followed the steps of [this guide](https://www.globo.tech/learning-center/sudo-unable-to-resolve-host-explained/) to the letter and it solved the issue for me.

**Comment by trathborne** [comment]
Yes, I tried that and all sorts of combinations and the behaviour has not changed.

**Comment by plumped** [comment]
JFY: Latest Core Version still existing

**Comment by PromoFaux** [comment]
Yep, latest core version is  a hotfix to get things working on Docker 20.10.14 - other fixes will come in Pi-hole 5.10

**Comment by fqx** [comment]
It seems that this is fixed in 5.10

**Comment by thisaccountname** [comment]
Just upgraded to 5.10 and I'm still experiencing this issue. 

Only difference is that it's my server looking itself up over and over, not my RPi running pihole. 

I am using local DNS records (b.box -> Server IP address), and that is the name that I see in the query log:

![image](https://user-images.githubusercontent.com/53269636/166339622-acfe9c8e-4fda-429a-871a-1ba309f9b27b.png)

**Comment by yubiuser** [comment]
We haven't heard of such a behaviour in a long time now - is this still an issue for someone?

**Comment by trathborne** [comment]
I have not seen this for a long time. My Pi died and I switched to the Docker image and it's not happening there either. I think you can close this! Thanks!
