### ISSUE TITLE
Cannot find NTP while NTP is running pihole V6

### ISSUE THREAD

**Issue by SlowFox72** [pi-hole/pi-hole#5907]
### Versions
Core version is v6.0 (Latest: v6.0)
Web version is v6.0 (Latest: v6.0)
FTL version is v6.0 (Latest: v6.0)

### Platform
- OS and version:  
Ubuntu Linux 22.04.5

### Actual behavior / bug

I'm getting the following error:

```
*** [ DIAGNOSING ]: Pi-hole diagnosis messages
   count   last timestamp       type                  message                                                       blob1                 blob2                 blob3                 blob4                 blob5
   ------  -------------------  --------------------  ------------------------------------------------------------  --------------------  --------------------  --------------------  --------------------  --------------------
   1       2025-02-19 09:31:59  NTP                   Cannot bind to IPv4 address 0.0.0.0:123 (Address in use), IP  Error                 server
                                                      v4 NTP server not available

   1       2025-02-19 09:31:59  NTP                   Cannot bind to IPv6 address :::123 (Address in use), IPv6 NT  Error                 server
                                                      P server not available
```

But i'm running locally NTP

```
ntpq -p
     remote           refid      st t when poll reach   delay   offset  jitter                                                               2024-02-05 17:49:22  2024-02-05
==============================================================================
 ntp.ubuntu.com  .POOL.          16 p    -   64    0    0.000   +0.000   0.000
-ntp.altinea.fr  240.67.35.84     3 u  183  512  377   16.502   -0.302   0.426
-ntp-2.arkena.ne 193.190.230.65   2 u  318  512  377   11.362   +0.116   0.297
-router-ix5.serv 121.103.170.45   3 u  332  512  377   20.206   -0.603   0.216                                                               2024-02-05 17:49:22  2024-02-05
-par.cyberbits.e 193.190.230.37   2 u  346  512  377   11.211   -1.201   0.439
-alphyn.canonica 132.163.96.1     2 u  134 1024  377   88.969   -2.383   0.423
+185.125.190.56  17.253.28.253    2 u  309  512  377   17.054   +0.061   0.392
+185.125.190.57  17.253.28.251    2 u  327  512  377   20.474   -2.366   0.626
*185.125.190.58  194.121.207.249  2 u  186  512  377   16.558   -0.514   0.448
```

## Debug Token
https://tricorder.pi-hole.net/kJOoxmjD/

**Comment by yubiuser** [comment]
As you already figured out, your're already running a NTP server locally 

```
    udp:172.17.0.1:123 is in use by ntpd
    udp:192.168.0.200:123 is in use by ntpd
    udp:127.0.0.1:123 is in use by ntpd
    udp:0.0.0.0:123 is in use by ntpd

```
This is why `pihole-FTL` can't bind to that port - it's already taken. There is likely not much gain to use Pi-hole also as NTP server, despite if you use it as DHCP server as well and want to advertise it's NTP capabilities to clients in the network.

You can simply disable NTP in Settings -> All Settings > NTP

**Comment by SlowFox72** [comment]
Great that solved my issue

**Comment by mrmuiz** [comment]
Same issue on Synology. 

Error NTP server: Cannot bind to IPv6 address :::123 (Address in use), IPv6 NTP server not available
Error NTP server: Cannot bind to IPv4 address 0.0.0.0:123 (Address in use), IPv4 NTP server not available

**Comment by yubiuser** [comment]
Same solution I guess: disable NTP in Pi-hole.

**Comment by mrmuiz** [comment]
> Same solution I guess: disable NTP in Pi-hole.

Yes thats possible. But why? The port is not in use.

**Comment by yubiuser** [comment]
Please generate a debug log and post the token

**Comment by mrmuiz** [comment]
> Please generate a debug log and post the token

![Image](https://github.com/user-attachments/assets/89cb296b-ee04-42ae-9bdf-b1876fd5e935)
Im sorry i  cant see  where.

**Comment by mrmuiz** [comment]
> Ah I see, you're running the Docker container. We don't have permissions to see other processes running. Maybe Synology does provide a NTP server itself?

Its only on one of the   nasses. I disabled all  other containers and  synoapps. Did : netstat -an and netstat -pat | grep LISTEN and netstat -lp
To see if there  was anything. But nothing to see.
Sended Synology Support Ticket. Cause now im curious.

If this cant be solved. Is there a way to set these settings in the docker compose ENV?

**Comment by yubiuser** [comment]
Sure

`FTLCONF_ntp_ipv4_active=false` and `FTLCONF_ntp_ipv6_active=false`

**Comment by diniket** [comment]
> Sure
> 
> `FTLCONF_ntp_ipv4_active=false` and `FTLCONF_ntp_ipv6_active=false`

work for me thaks

**Comment by mrmuiz** [comment]
> `FTLCONF_ntp_ipv4_active=false` and `FTLCONF_ntp_ipv6_active=false`

It works. Only when set it  in the ENV. Then it cannot be enabled anymore in Pihole.  Unclickable.
Same goes for ;       - FTLCONF_ntp_sync_server=0.nl.pool.ntp.org after  set this in the ENV. You cannot change it anymore in Pihole.
Is this normal?

**Comment by yubiuser** [comment]
> Is this normal?

Yes, this is by design to avoid dealing with conflicting settings from config files vs. env variables. There should only be 'one source of truth'

**Comment by mrmuiz** [comment]
> > Is this normal?
> 
> Yes, this is by design to avoid dealing with conflicting settings from config files vs. env variables. There should only be 'one source of truth'

Not very ideal if you ask me. But good to know. Saves headaches not knowing why you cant change it anymore.

**Comment by mrmuiz** [comment]
Figured it out :  DNSMASQ_USER: root This was set as : pihole. And then you get the NTP error.

**Comment by yubiuser** [comment]
@mrmuiz 

Try adding `SYS_TIME` to the containers capabilities. This should fix it as well.

**Comment by diniket** [comment]
So it should be set to root?

**Comment by mrmuiz** [comment]
> [@mrmuiz](https://github.com/mrmuiz)
> 
> Try adding `SYS_TIME` to the containers capabilities. This should fix it as well.

This does not fix it. I let a few people test. And only thing that works is set to root. But the log says ```Starting pihole-FTL as user root is not recommended``` i used to set it to root cause im on Synology. Now in v6 i can use Pihole. But then we get the NTP error. Where is the NTP option in Pihole for if i may ask?

**Comment by yubiuser** [comment]
> Where is the NTP option in Pihole for if i may ask?

Settings > All Settings > NTP > IPv4/6.activate

**Comment by mrmuiz** [comment]
> > Where is the NTP option in Pihole for if i may ask?
> 
> Settings > All Settings > NTP > IPv4/6.activate

Im sorry. I ment what does it do. What is the use?

**Comment by diniket** [comment]
Is used to synchronize the time

**Comment by TheEngineerGuy** [comment]
I have NTP server running on my gateway address. The OS is able to sync NTP from that gateway, but pinhole keeps complaining: `No valid NTP replies received, check server and network connectivity`

Even though I know for a fact that this NTP is running and responding back to the OS.
```timedatectl
               Local time: Tue 2026-03-03 09:30:11 MST
           Universal time: Tue 2026-03-03 16:30:11 UTC
                 RTC time: n/a
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no

**Comment by SlowFox72** [comment]
@TheEngineerGuy and if you simply disable NTP in PiHole? 
 Settings -> All Settings > NTP

**Comment by TheEngineerGuy** [comment]
Then the error would go away! But that isnt why I am posting here :). 

Trying to understand why pihole is not syncing from an active NTP service.

**Comment by rdwebdesign** [comment]
@TheEngineerGuy 

This issue was closed more than 1 year ago.

If your Pi-hole has a problem, please open a new issue including all details and also a debug token.
