### ISSUE TITLE
Pi-Hole requiring login password after 6.0.3 upgrade

### ISSUE THREAD

**Issue by Caligatio** [pi-hole/pi-hole#5959]
### Versions

- Pi-hole:  6.0.3
- AdminLTE:  6.0.1
- FTL:   6.0.2

### Platform

- OS and version:  Debian 12

- Platform:  LXC container

### Expected behavior

My password-less pi-hole install should not prompt me for a password after upgrading to v6.0.3

### Actual behavior / bug

Following the v6.0.3 upgrade (likely due to #5935), my previously password-less pi-hole install prompted me for a password when accessing the web GUI. Setting the password to blank again fixed the problem.

### Steps to reproduce

1. Use pi-hole < v6.0.3
2. Set the pi-hole password to blank
3. Upgrade to v6.0.3
4. Be prompted for a password

## Debug Token

N/A

### Screenshots

N/A

### Additional context
N/A

**Comment by yubiuser** [comment]
Thanks. Should be fixed with https://github.com/pi-hole/pi-hole/pull/5960

**Comment by AliveDevil** [comment]
Not fixed, still happens on 6.0.4.
`pihole setpassword` to remove, restart container - creates a random password again.

**Comment by rdwebdesign** [comment]
Thanks for reporting. We will investigate.

**Comment by PromoFaux** [comment]
@AliveDevil you're seeing something different to the OP of this issue, who isn't using docker.

However:

From: https://github.com/pi-hole/docker-pi-hole/#web-interface-password

> To explicitly set no password, set `FTLCONF_webserver_api_password: ''`

Set that as an environment variable

**Comment by AliveDevil** [comment]
Gotcha, thank you @PromoFaux.
Wasn't immediately obvious that 'setting an empty password' with `pihole setpassword` wasn't "setting a password". Though personally, this feels more like a workaround.

If this is expected behavior, this needs further clarification because `pihole setpassword` allows an empty password and restarts will generate a random password, or this isn't expected behavior, and should be looked at.
I.e. "If this variable is not detected, and you have not already set one previously inside the container via pihole setpassword or pihole-FTL --config webserver.api.password"
Should then read "If this variable is not detected, and you have not already set a non-empty password inside the container …" - emphasis on non-empty instead of "set one".

**Comment by brandonforster** [comment]
I ran into this problem today and wanted to make sure it's documented somewhere so someone doesn't have to find out the hard way like I did:


The YAML must be a **map**. It will not work with a **list.**

Incorrect YAML:
```yaml
environment:
  - TZ=America/Chicago
  - FTLCONF_webserver_api_password=''
```

Correct:
```yaml
environment:
  TZ: America/Chicago
  FTLCONF_webserver_api_password: ''
```
