### ISSUE TITLE
Local DNS doesn't work

### ISSUE THREAD

**Issue by enjunear** [pi-hole/pi-hole#6164]
### Versions

- Pi-hole:  Core version is v6.0.6 (Latest: v6.0.6)
- AdminLTE:  Web version is v6.1 (Latest: v6.1)
- FTL:  FTL version is v6.1 (Latest: v6.1)

### Platform

- OS and version:  Raspberry Pi OS

- Platform:  Linux 6.6.51+rpt-rpi-v7 #1 SMP Raspbian 1:6.6.51-1+rpt3 (2024-10-08) armv7l

### Expected behavior

_A clear and concise description of what you expected to happen._

Local DNS to resolve.

### Actual behavior / bug

_A clear and concise description of what the bug is._

Local DNS entries don't resolve.

### Steps to reproduce

1. Fresh install Raspberry Pi OS
2. Fresh install pi-hole using `curl -sSL https://install.pi-hole.net | bash`
3. Set up local DNS entries
4. Try to navigate to one of the local servers
5. `NS_ERROR_CONNECTION_REFUSED`

## Debug Token

- URL:  https://tricorder.pi-hole.net/dICX6Rfs/

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

Would appreciate a way to roll back to v5

**Comment by dschaper** [comment]
It doesn't look like you have a hosts entry for `grafana`.

Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we ask that all configuration questions be addressed at our  [Discourse](https://discourse.pi-hole.net) forum.

Thank you for your understanding.

**Comment by enjunear** [comment]
Well tickle me pink. I didn't put grafana in on that fresh install.

but every other service doesn't resolve either.

I'd be happy to use your discourse forum, but I can't post there.
