### ISSUE TITLE
Attempts to manipulate allow list via CLI produces "/opt/pihole/api.sh: line 25: PI_HOLE_SCRIPT_DIR: readonly variable" and no domain is added

### ISSUE THREAD

**Issue by zerbey** [pi-hole/pi-hole#6357]
### Versions

Core version is v6.1.4 (Latest: v6.1.4)
Web version is v6.2.1 (Latest: v6.2.1)
FTL version is v6.2.3 (Latest: v6.2.3)

### Platform

- OS and version:  Ubuntu 22.04 

- Platform:  x64

### Expected behavior

Attempting to add domains to allow list should produce output and the domain should be added

### Actual behavior / bug

The output produces an error and does not add the domain to the allow list:

```
$ sudo pihole allow testsite.com
[sudo] password for user:
/opt/pihole/api.sh: line 25: PI_HOLE_SCRIPT_DIR: readonly variable

$ sudo pihole query testsite.com
Found 0 domains exactly matching 'testsite.com'.

Found 0 adlists exactly matching 'testsite.com'.

Hint: Try partial matching with
  pihole -q --partial testsite.com
```

Workaround: Can add domains via web interface 

### Steps to reproduce

1. Open command prompt
2. Use "sudo pihole allow domain.com"
3. Use "sudo pihole query test.com" to verify if site has been added

## Debug Token

- URL:  https://tricorder.pi-hole.net/UR0fHedC/

**Comment by rdwebdesign** [comment]
This is already fixed in `development` branch: https://github.com/pi-hole/pi-hole/pull/6349

**Comment by dschaper** [comment]
https://discourse.pi-hole.net/t/domain-commands-fail-with-pi-hole-script-dir-readonly-variable-error/81176/5

**Comment by HuckToohey** [comment]
Can verify issue still exists.

`$ sudo pihole -up --check-only
  [✓] Building dependency package pihole-meta.deb
  [✓] Installing Pi-hole dependency package

  [i] Checking for updates...
  [i] Pi-hole Core:     up to date
  [i] Web Interface:    up to date
  [i] FTL:              up to date

  [✓] Everything is up to date!

$ sudo pihole allow adaway.org
/opt/pihole/api.sh: line 25: PI_HOLE_SCRIPT_DIR: readonly variable
`

**Comment by HuckToohey** [comment]
Are these permissions correct?

`$ ls -l /opt/pihole/api.sh
-rwxr-xr-x 1 root root 12141 Sep 14 18:03 /opt/pihole/api.sh

$ ls -l /opt/pihole/utils.sh
-rwxr-xr-x 1 root root 2959 Sep 14 18:03 /opt/pihole/utils.sh
`

**Comment by kylebeggs** [comment]
Is there a way to hotfix this while we wait for the next release? I tried just manually editing the file, but it didn't work.

**Comment by TechnicallyBob202** [comment]
still doesn't work.

pihole -v 
Core version is v6.1.4 (Latest: v6.1.4)
Web version is v6.2.1 (Latest: v6.2.1)
FTL version is v6.2.3 (Latest: v6.2.3)

**Comment by kylebeggs** [comment]
@TechnicallyBob202  The fix for it is not included in v6.1.4, it was merged into main right after that release, so we need another release. FYI you can still use the webpage UI - just tedious to do so as its one by one.

**Comment by rdwebdesign** [comment]
> it was merged into main right after that release

Actually it was merged into `development` branch. The development branch will be merged into `master` for the next release. Until then, you can use the development branch or wait.

**Comment by pozdrowiony** [comment]
I've checked both /opt/pihole/utils.sh and /opt/pihole/api.sh and confirm they don't contain `readonly` statements but still getting `/opt/pihole/api.sh: line 25: PI_HOLE_SCRIPT_DIR: readonly variable`

Core version is v6.1.4 (Latest: v6.1.4)
Web version is v6.2.1 (Latest: v6.2.1)
FTL version is v6.2.3 (Latest: v6.2.3)

**Comment by yubiuser** [comment]
Should be fixed with https://github.com/pi-hole/pi-hole/releases/tag/v6.2
